<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../GenerateFaultProcess.wsdl"/>
      <rootElement name="process" namespace="http://xmlns.oracle.com/SOA_Application_jws/MessageResubmitter/GenerateFaultProcess"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/FaultNotification.xsd"/>
      <rootElement name="Fault" namespace="http://www.turktelekom.com.tr/aTTIP/Schemas/Utilities/CentralizedFaultManagement/Fault/1.0"/>
    </target>
  </mapTargets>
  <substitutions>
      <sourceSubst substPath="/client:process" substType="mr:ResubmittionRequestType"/>
  </substitutions>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.3.0(build 100415.2045.2557) AT [TUE JUN 15 13:06:48 CEST 2010]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:mr="http://www.turktelekom.com.tr/aTTIP/Schemas/Utilities/CentralizedFaultManagement/MessageResubmitter/1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel2="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:client="http://xmlns.oracle.com/SOA_Application_jws/MessageResubmitter/GenerateFaultProcess"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:fault="http://www.turktelekom.com.tr/aTTIP/Schemas/Utilities/CentralizedFaultManagement/Fault/1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl mr client plnk xsd wsdl fault bpws xp20 mhdr bpel2 oraext dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:template match="/">
    <fault:Fault>
      <fault:Code>
        <xsl:text disable-output-escaping="no">aaaaaaa</xsl:text>
      </fault:Code>
      <fault:Description>
        <xsl:text disable-output-escaping="no">message to be resubmited</xsl:text>
      </fault:Description>
      <fault:SourceSystem>
        <xsl:text disable-output-escaping="no">osb?</xsl:text>
      </fault:SourceSystem>
    </fault:Fault>
  </xsl:template>
</xsl:stylesheet>
