package org.realtor.rets.database.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the properties table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="properties"
 */
public abstract class BaseProperties  implements Serializable {

	public static String PROP_MONTHELECTRIC = "Monthelectric";
	public static String PROP_PROPTYPE = "Proptype";
	public static String PROP_PUBLICTRANS = "Publictrans";
	public static String PROP_COMPSELL = "Compsell";
	public static String PROP_COOLSYSTEM = "Coolsystem";
	public static String PROP_BED4DIM = "Bed4dim";
	public static String PROP_MAPPAGE = "Mappage";
	public static String PROP_STYLE = "Style";
	public static String PROP_ROOMOTHER3NAME = "Roomother3name";
	public static String PROP_SHOWINSTR = "Showinstr";
	public static String PROP_STREETNAME = "Streetname";
	public static String PROP_ROOMS = "Rooms";
	public static String PROP_SUBDIVISION = "Subdivision";
	public static String PROP_RESTRICTIONS = "Restrictions";
	public static String PROP_SQFTFINISHED = "Sqftfinished";
	public static String PROP_CITY = "City";
	public static String PROP_ZIPCODE = "Zipcode";
	public static String PROP_MAP = "Map";
	public static String PROP_MLSNUM_CRIS = "MlsnumCris";
	public static String PROP_BATHSTOTAL = "Bathstotal";
	public static String PROP_PROPSUBTYPE = "Propsubtype";
	public static String PROP_WATER = "Water";
	public static String PROP_PHOTOCODE = "Photocode";
	public static String PROP_PHOTOINSTR = "Photoinstr";
	public static String PROP_ROOMMASTERBEDDIM = "Roommasterbeddim";
	public static String PROP_CLOSEDBY = "Closedby";
	public static String PROP_BED2DESC = "Bed2desc";
	public static String PROP_FINANCEACCEPTABLE = "Financeacceptable";
	public static String PROP_UNITFLOORNUM = "Unitfloornum";
	public static String PROP_LOTNUM = "Lotnum";
	public static String PROP_LISTTYPE = "Listtype";
	public static String PROP_ROOMDININGDESC = "Roomdiningdesc";
	public static String PROP_ROOMDININGDIM = "Roomdiningdim";
	public static String PROP_STATE = "State";
	public static String PROP_NUMFLOORS = "Numfloors";
	public static String PROP_MAINTFEE = "Maintfee";
	public static String PROP_ZONING = "Zoning";
	public static String PROP_ROOMOTHER3LEVEL = "Roomother3level";
	public static String PROP_ROOMOTHER3DESC = "Roomother3desc";
	public static String PROP_ROOMOTHER = "Roomother";
	public static String PROP_SIDING = "Siding";
	public static String PROP_ACRES = "Acres";
	public static String PROP_AREA = "Area";
	public static String PROP_TEMPOFFMARKETDATE = "Tempoffmarketdate";
	public static String PROP_ROOMLIVINGLEVEL = "Roomlivinglevel";
	public static String PROP_OWNERAGENT = "Owneragent";
	public static String PROP_ASSOCFEEPAID = "Assocfeepaid";
	public static String PROP_BED3LEVEL = "Bed3level";
	public static String PROP_BED2LEVEL = "Bed2level";
	public static String PROP_AGENTSELL = "Agentsell";
	public static String PROP_OFFMARKETDATE = "Offmarketdate";
	public static String PROP_BATHSHALF = "Bathshalf";
	public static String PROP_MAPCOUNTY = "Mapcounty";
	public static String PROP_LOTDIM = "Lotdim";
	public static String PROP_OFFICESELL = "Officesell";
	public static String PROP_OCCUPIED = "Occupied";
	public static String PROP_ROOMOTHER3DIM = "Roomother3dim";
	public static String PROP_MLSTYPE = "Mlstype";
	public static String PROP_FENCE = "Fence";
	public static String PROP_SELLING_AGENT = "SellingAgent";
	public static String PROP_PENDINGDATE = "Pendingdate";
	public static String PROP_BASEMENT = "Basement";
	public static String PROP_REALREMARKS = "Realremarks";
	public static String PROP_ZIP4 = "Zip4";
	public static String PROP_MODIFIED = "Modified";
	public static String PROP_BED5DIM = "Bed5dim";
	public static String PROP_SQFTUNFINISHED = "Sqftunfinished";
	public static String PROP_STORIES = "Stories";
	public static String PROP_BED5LEVEL = "Bed5level";
	public static String PROP_LISTDATERECEIVED = "Listdatereceived";
	public static String PROP_ROOMOTHER2NAME = "Roomother2name";
	public static String PROP_BED3DIM = "Bed3dim";
	public static String PROP_NEWCONSTRUCTION = "Newconstruction";
	public static String PROP_ROOMKITCHENLEVEL = "Roomkitchenlevel";
	public static String PROP_ROOMFAMILYDESC = "Roomfamilydesc";
	public static String PROP_DIRECTIONS = "Directions";
	public static String PROP_MONTHWATER = "Monthwater";
	public static String PROP_ROOMOTHER1DIM = "Roomother1dim";
	public static String PROP_MLSNUM = "Mlsnum";
	public static String PROP_AGENTLISTING = "Agentlisting";
	public static String PROP_SQFTTOTAL = "Sqfttotal";
	public static String PROP_ROOMOTHER1LEVEL = "Roomother1level";
	public static String PROP_HANDICAP = "Handicap";
	public static String PROP_BATHSFULL = "Bathsfull";
	public static String PROP_PHOTODATE = "Photodate";
	public static String PROP_WITHDRAWNDATE = "Withdrawndate";
	public static String PROP_STREETDIR = "Streetdir";
	public static String PROP_POSSESSION = "Possession";
	public static String PROP_LOCKBOXDESC = "Lockboxdesc";
	public static String PROP_ROOMOTHER2DESC = "Roomother2desc";
	public static String PROP_ROOF = "Roof";
	public static String PROP_SCHOOLDISTRICT_DISPLAY = "SchooldistrictDisplay";
	public static String PROP_ROOMFAMILYLEVEL = "Roomfamilylevel";
	public static String PROP_APPLIANCES = "Appliances";
	public static String PROP_AUCTION = "Auction";
	public static String PROP_BED4DESC = "Bed4desc";
	public static String PROP_CLOSEDDATE = "Closeddate";
	public static String PROP_DAYSONMARKET = "Daysonmarket";
	public static String PROP_SELLING_COMPANY = "SellingCompany";
	public static String PROP_BED5DESC = "Bed5desc";
	public static String PROP_ROOMDENDIM = "Roomdendim";
	public static String PROP_ASSOCFEE = "Assocfee";
	public static String PROP_ROOMLIVINGDESC = "Roomlivingdesc";
	public static String PROP_UID = "Uid";
	public static String PROP_COMPBUY = "Compbuy";
	public static String PROP_PHOTOCOUNT = "Photocount";
	public static String PROP_EXPIREDATE = "Expiredate";
	public static String PROP_ROOMKITCHENDESC = "Roomkitchendesc";
	public static String PROP_MULTIPLEPIN = "Multiplepin";
	public static String PROP_TAXAMOUNT = "Taxamount";
	public static String PROP_ROOMDENDESC = "Roomdendesc";
	public static String PROP_ROOMFAMILYDIM = "Roomfamilydim";
	public static String PROP_BEDS = "Beds";
	public static String PROP_ROOMDENLEVEL = "Roomdenlevel";
	public static String PROP_ROOMOTHER1NAME = "Roomother1name";
	public static String PROP_LISTPRICEORIG = "Listpriceorig";
	public static String PROP_SCHOOLDISTRICT = "Schooldistrict";
	public static String PROP_GARAGEDESC = "Garagedesc";
	public static String PROP_AGENTCOSELL = "Agentcosell";
	public static String PROP_EXTERIOR = "Exterior";
	public static String PROP_LOTRENT = "Lotrent";
	public static String PROP_LONGITUDE = "Longitude";
	public static String PROP_LISTPRICE = "Listprice";
	public static String PROP_BED2DIM = "Bed2dim";
	public static String PROP_LISTING_COMPANY = "ListingCompany";
	public static String PROP_BED4LEVEL = "Bed4level";
	public static String PROP_OID = "Oid";
	public static String PROP_WARRANTY = "Warranty";
	public static String PROP_ROOMOTHER1DESC = "Roomother1desc";
	public static String PROP_PARKINGCOVERED = "Parkingcovered";
	public static String PROP_FRONTAGEFEET = "Frontagefeet";
	public static String PROP_STREETNUM = "Streetnum";
	public static String PROP_AGENTCOLIST = "Agentcolist";
	public static String PROP_MAINTFEEINCLUDES = "Maintfeeincludes";
	public static String PROP_ROOMOTHER2LEVEL = "Roomother2level";
	public static String PROP_STREETNUMDISPLAY = "Streetnumdisplay";
	public static String PROP_COUNTY = "County";
	public static String PROP_SQFTSOURCE = "Sqftsource";
	public static String PROP_ROOMMASTERBEDDESC = "Roommasterbeddesc";
	public static String PROP_LISTING_AGENT = "ListingAgent";
	public static String PROP_RECREATIONFEE = "Recreationfee";
	public static String PROP_LOTDESC = "Lotdesc";
	public static String PROP_ROOMKITCHENDIM = "Roomkitchendim";
	public static String PROP_MONTHGAS = "Monthgas";
	public static String PROP_FIREPLACES = "Fireplaces";
	public static String PROP_CONTINGENCY = "Contingency";
	public static String PROP_SELLERPOINTS = "Sellerpoints";
	public static String PROP_ROOMMASTERBEDLEVEL = "Roommasterbedlevel";
	public static String PROP_LISTSTATUS = "Liststatus";
	public static String PROP_OFFICELISTING = "Officelisting";
	public static String PROP_YEARBUILT = "Yearbuilt";
	public static String PROP_FINANCECODE = "Financecode";
	public static String PROP_COMPOTHER = "Compother";
	public static String PROP_VIEWDESC = "Viewdesc";
	public static String PROP_HOMEOWNERSASSOC = "Homeownersassoc";
	public static String PROP_REMARKS = "Remarks";
	public static String PROP_AMENITIES = "Amenities";
	public static String PROP_HEATSRC = "Heatsrc";
	public static String PROP_SCHOOLHIGH = "Schoolhigh";
	public static String PROP_MLSCROSSREF = "Mlscrossref";
	public static String PROP_UIDPRP = "Uidprp";
	public static String PROP_ROOMOTHER2DIM = "Roomother2dim";
	public static String PROP_BED3DESC = "Bed3desc";
	public static String PROP_SALESPRICE = "Salesprice";
	public static String PROP_ROOMLIVINGDIM = "Roomlivingdim";
	public static String PROP_TAXPARCEL = "Taxparcel";
	public static String PROP_INTERNETLIST = "Internetlist";
	public static String PROP_LATITUDE = "Latitude";
	public static String PROP_ROOMDININGLEVEL = "Roomdininglevel";
	public static String PROP_LISTDATE = "Listdate";
	public static String PROP_HEATSYSTEM = "Heatsystem";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _oid;

	// fields
	private java.math.BigDecimal _sqfttotal;
	private java.lang.String _map;
	private java.lang.String _state;
	private java.lang.String _roomother3dim;
	private java.lang.Integer _listingCompany;
	private java.lang.String _roomdininglevel;
	private java.util.Date _expiredate;
	private java.lang.String _officelisting;
	private java.lang.String _photoinstr;
	private java.lang.String _roof;
	private java.lang.String _roomother1desc;
	private java.lang.String _basement;
	private java.lang.String _proptype;
	private java.lang.String _roomother1dim;
	private java.lang.String _mapcounty;
	private java.lang.String _bed5desc;
	private java.lang.String _agentcosell;
	private java.lang.String _roommasterbeddim;
	private java.lang.String _roomdenlevel;
	private java.lang.String _showinstr;
	private java.lang.String _roomfamilydesc;
	private java.lang.String _restrictions;
	private java.math.BigDecimal _recreationfee;
	private java.lang.String _roomother1name;
	private java.math.BigDecimal _photocount;
	private java.lang.String _assocfeepaid;
	private java.lang.String _homeownersassoc;
	private java.lang.String _heatsrc;
	private java.lang.String _roomdiningdim;
	private java.lang.String _roomdendesc;
	private java.math.BigDecimal _mappage;
	private java.lang.String _lotdesc;
	private java.lang.String _county;
	private java.lang.String _bed3desc;
	private java.lang.String _city;
	private java.math.BigDecimal _monthwater;
	private java.lang.String _bed3level;
	private java.math.BigDecimal _latitude;
	private java.lang.String _schooldistrict;
	private java.lang.String _streetnumdisplay;
	private java.math.BigDecimal _maintfee;
	private java.math.BigDecimal _bathsfull;
	private java.lang.String _bed4dim;
	private java.util.Date _photodate;
	private java.lang.String _roomkitchenlevel;
	private java.lang.String _appliances;
	private java.math.BigDecimal _listprice;
	private java.math.BigDecimal _daysonmarket;
	private java.lang.String _publictrans;
	private java.lang.String _roomkitchendim;
	private java.lang.String _lotrent;
	private java.lang.String _schoolhigh;
	private java.lang.String _streetname;
	private java.math.BigDecimal _sellerpoints;
	private java.lang.String _roomother3level;
	private java.lang.String _mlstype;
	private java.math.BigDecimal _taxamount;
	private java.lang.String _bed2dim;
	private java.lang.String _bed5dim;
	private java.lang.String _roomfamilydim;
	private java.math.BigDecimal _assocfee;
	private java.lang.String _lotnum;
	private java.math.BigDecimal _salesprice;
	private java.util.Date _listdate;
	private java.lang.String _zoning;
	private java.lang.String _propsubtype;
	private java.lang.String _agentlisting;
	private java.util.Date _closeddate;
	private java.lang.String _fence;
	private java.lang.String _contingency;
	private java.math.BigDecimal _longitude;
	private java.lang.String _streetdir;
	private java.lang.Integer _sellingAgent;
	private java.lang.String _mlscrossref;
	private java.lang.String _closedby;
	private java.math.BigDecimal _monthgas;
	private java.lang.String _financecode;
	private java.lang.String _roomother3desc;
	private java.lang.String _style;
	private java.lang.Long _uid;
	private java.lang.String _unitfloornum;
	private java.lang.String _roomother3name;
	private java.lang.String _possession;
	private java.math.BigDecimal _bathshalf;
	private java.lang.String _bed2level;
	private java.math.BigDecimal _parkingcovered;
	private java.lang.String _handicap;
	private java.lang.String _roomfamilylevel;
	private java.lang.String _lockboxdesc;
	private java.lang.String _officesell;
	private java.math.BigDecimal _sqftunfinished;
	private java.math.BigDecimal _sqftfinished;
	private java.lang.String _maintfeeincludes;
	private java.lang.String _bed4desc;
	private java.lang.String _lotdim;
	private java.util.Date _offmarketdate;
	private java.lang.String _roomother;
	private java.lang.String _roomlivingdim;
	private java.lang.String _bed3dim;
	private java.lang.String _garagedesc;
	private java.lang.String _heatsystem;
	private java.lang.String _photocode;
	private java.util.Date _withdrawndate;
	private java.lang.String _roomother2level;
	private java.util.Date _modified;
	private java.lang.String _exterior;
	private java.lang.String _liststatus;
	private java.lang.String _roomdiningdesc;
	private java.lang.String _financeacceptable;
	private java.math.BigDecimal _area;
	private java.lang.String _coolsystem;
	private java.lang.Integer _listingAgent;
	private java.lang.String _roomother2dim;
	private java.lang.String _amenities;
	private java.lang.String _compother;
	private java.lang.String _mlsnumCris;
	private java.lang.String _viewdesc;
	private java.util.Date _listdatereceived;
	private java.lang.String _roomother1level;
	private java.lang.String _siding;
	private java.math.BigDecimal _yearbuilt;
	private java.lang.String _bed5level;
	private java.math.BigDecimal _beds;
	private java.lang.String _roommasterbedlevel;
	private java.math.BigDecimal _listpriceorig;
	private java.lang.String _subdivision;
	private java.lang.String _warranty;
	private java.lang.String _water;
	private java.lang.String _roomlivingdesc;
	private java.lang.String _auction;
	private java.lang.String _roomlivinglevel;
	private java.lang.String _bed2desc;
	private java.lang.String _internetlist;
	private java.math.BigDecimal _zipcode;
	private java.lang.String _agentsell;
	private java.lang.String _taxparcel;
	private java.util.Date _tempoffmarketdate;
	private java.lang.String _remarks;
	private java.lang.String _owneragent;
	private java.lang.String _uidprp;
	private java.lang.String _fireplaces;
	private java.lang.String _roommasterbeddesc;
	private java.lang.String _schooldistrictDisplay;
	private java.math.BigDecimal _stories;
	private java.lang.String _roomdendim;
	private java.lang.String _streetnum;
	private java.math.BigDecimal _zip4;
	private java.lang.Integer _sellingCompany;
	private java.math.BigDecimal _acres;
	private java.math.BigDecimal _compsell;
	private java.lang.String _mlsnum;
	private java.lang.String _directions;
	private java.lang.String _roomkitchendesc;
	private java.lang.String _sqftsource;
	private java.math.BigDecimal _numfloors;
	private java.math.BigDecimal _frontagefeet;
	private java.util.Date _pendingdate;
	private java.lang.String _multiplepin;
	private java.lang.String _realremarks;
	private java.math.BigDecimal _bathstotal;
	private java.lang.String _roomother2name;
	private java.math.BigDecimal _compbuy;
	private java.lang.String _newconstruction;
	private java.math.BigDecimal _rooms;
	private java.lang.String _agentcolist;
	private java.lang.String _occupied;
	private java.math.BigDecimal _monthelectric;
	private java.lang.String _bed4level;
	private java.lang.String _roomother2desc;
	private java.lang.String _listtype;

	// collections
	private java.util.Set _agents;


	// constructors
	public BaseProperties () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseProperties (java.lang.Long _oid) {
		this.setOid(_oid);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="OID"
     */
	public java.lang.Long getOid () {
		return _oid;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _oid the new ID
	 */
	public void setOid (java.lang.Long _oid) {
		this._oid = _oid;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: SQFTTOTAL
	 */
	public java.math.BigDecimal getSqfttotal () {
		return _sqfttotal;
	}

	/**
	 * Set the value related to the column: SQFTTOTAL
	 * @param _sqfttotal the SQFTTOTAL value
	 */
	public void setSqfttotal (java.math.BigDecimal _sqfttotal) {
		this._sqfttotal = _sqfttotal;
	}


	/**
	 * Return the value associated with the column: MAP
	 */
	public java.lang.String getMap () {
		return _map;
	}

	/**
	 * Set the value related to the column: MAP
	 * @param _map the MAP value
	 */
	public void setMap (java.lang.String _map) {
		this._map = _map;
	}


	/**
	 * Return the value associated with the column: STATE
	 */
	public java.lang.String getState () {
		return _state;
	}

	/**
	 * Set the value related to the column: STATE
	 * @param _state the STATE value
	 */
	public void setState (java.lang.String _state) {
		this._state = _state;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER3DIM
	 */
	public java.lang.String getRoomother3dim () {
		return _roomother3dim;
	}

	/**
	 * Set the value related to the column: ROOMOTHER3DIM
	 * @param _roomother3dim the ROOMOTHER3DIM value
	 */
	public void setRoomother3dim (java.lang.String _roomother3dim) {
		this._roomother3dim = _roomother3dim;
	}


	/**
	 * Return the value associated with the column: LISTING_COMPANY
	 */
	public java.lang.Integer getListingCompany () {
		return _listingCompany;
	}

	/**
	 * Set the value related to the column: LISTING_COMPANY
	 * @param _listingCompany the LISTING_COMPANY value
	 */
	public void setListingCompany (java.lang.Integer _listingCompany) {
		this._listingCompany = _listingCompany;
	}


	/**
	 * Return the value associated with the column: ROOMDININGLEVEL
	 */
	public java.lang.String getRoomdininglevel () {
		return _roomdininglevel;
	}

	/**
	 * Set the value related to the column: ROOMDININGLEVEL
	 * @param _roomdininglevel the ROOMDININGLEVEL value
	 */
	public void setRoomdininglevel (java.lang.String _roomdininglevel) {
		this._roomdininglevel = _roomdininglevel;
	}


	/**
	 * Return the value associated with the column: EXPIREDATE
	 */
	public java.util.Date getExpiredate () {
		return _expiredate;
	}

	/**
	 * Set the value related to the column: EXPIREDATE
	 * @param _expiredate the EXPIREDATE value
	 */
	public void setExpiredate (java.util.Date _expiredate) {
		this._expiredate = _expiredate;
	}


	/**
	 * Return the value associated with the column: OFFICELIST
	 */
	public java.lang.String getOfficelisting () {
		return _officelisting;
	}

	/**
	 * Set the value related to the column: OFFICELIST
	 * @param _officelisting the OFFICELIST value
	 */
	public void setOfficelisting (java.lang.String _officelisting) {
		this._officelisting = _officelisting;
	}


	/**
	 * Return the value associated with the column: PHOTOINSTR
	 */
	public java.lang.String getPhotoinstr () {
		return _photoinstr;
	}

	/**
	 * Set the value related to the column: PHOTOINSTR
	 * @param _photoinstr the PHOTOINSTR value
	 */
	public void setPhotoinstr (java.lang.String _photoinstr) {
		this._photoinstr = _photoinstr;
	}


	/**
	 * Return the value associated with the column: ROOF
	 */
	public java.lang.String getRoof () {
		return _roof;
	}

	/**
	 * Set the value related to the column: ROOF
	 * @param _roof the ROOF value
	 */
	public void setRoof (java.lang.String _roof) {
		this._roof = _roof;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER1DESC
	 */
	public java.lang.String getRoomother1desc () {
		return _roomother1desc;
	}

	/**
	 * Set the value related to the column: ROOMOTHER1DESC
	 * @param _roomother1desc the ROOMOTHER1DESC value
	 */
	public void setRoomother1desc (java.lang.String _roomother1desc) {
		this._roomother1desc = _roomother1desc;
	}


	/**
	 * Return the value associated with the column: BASEMENT
	 */
	public java.lang.String getBasement () {
		return _basement;
	}

	/**
	 * Set the value related to the column: BASEMENT
	 * @param _basement the BASEMENT value
	 */
	public void setBasement (java.lang.String _basement) {
		this._basement = _basement;
	}


	/**
	 * Return the value associated with the column: PROPTYPE
	 */
	public java.lang.String getProptype () {
		return _proptype;
	}

	/**
	 * Set the value related to the column: PROPTYPE
	 * @param _proptype the PROPTYPE value
	 */
	public void setProptype (java.lang.String _proptype) {
		this._proptype = _proptype;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER1DIM
	 */
	public java.lang.String getRoomother1dim () {
		return _roomother1dim;
	}

	/**
	 * Set the value related to the column: ROOMOTHER1DIM
	 * @param _roomother1dim the ROOMOTHER1DIM value
	 */
	public void setRoomother1dim (java.lang.String _roomother1dim) {
		this._roomother1dim = _roomother1dim;
	}


	/**
	 * Return the value associated with the column: MAPCOUNTY
	 */
	public java.lang.String getMapcounty () {
		return _mapcounty;
	}

	/**
	 * Set the value related to the column: MAPCOUNTY
	 * @param _mapcounty the MAPCOUNTY value
	 */
	public void setMapcounty (java.lang.String _mapcounty) {
		this._mapcounty = _mapcounty;
	}


	/**
	 * Return the value associated with the column: BED5DESC
	 */
	public java.lang.String getBed5desc () {
		return _bed5desc;
	}

	/**
	 * Set the value related to the column: BED5DESC
	 * @param _bed5desc the BED5DESC value
	 */
	public void setBed5desc (java.lang.String _bed5desc) {
		this._bed5desc = _bed5desc;
	}


	/**
	 * Return the value associated with the column: AGENTCOSELL
	 */
	public java.lang.String getAgentcosell () {
		return _agentcosell;
	}

	/**
	 * Set the value related to the column: AGENTCOSELL
	 * @param _agentcosell the AGENTCOSELL value
	 */
	public void setAgentcosell (java.lang.String _agentcosell) {
		this._agentcosell = _agentcosell;
	}


	/**
	 * Return the value associated with the column: ROOMMASTERBEDDIM
	 */
	public java.lang.String getRoommasterbeddim () {
		return _roommasterbeddim;
	}

	/**
	 * Set the value related to the column: ROOMMASTERBEDDIM
	 * @param _roommasterbeddim the ROOMMASTERBEDDIM value
	 */
	public void setRoommasterbeddim (java.lang.String _roommasterbeddim) {
		this._roommasterbeddim = _roommasterbeddim;
	}


	/**
	 * Return the value associated with the column: ROOMDENLEVEL
	 */
	public java.lang.String getRoomdenlevel () {
		return _roomdenlevel;
	}

	/**
	 * Set the value related to the column: ROOMDENLEVEL
	 * @param _roomdenlevel the ROOMDENLEVEL value
	 */
	public void setRoomdenlevel (java.lang.String _roomdenlevel) {
		this._roomdenlevel = _roomdenlevel;
	}


	/**
	 * Return the value associated with the column: SHOWINSTR
	 */
	public java.lang.String getShowinstr () {
		return _showinstr;
	}

	/**
	 * Set the value related to the column: SHOWINSTR
	 * @param _showinstr the SHOWINSTR value
	 */
	public void setShowinstr (java.lang.String _showinstr) {
		this._showinstr = _showinstr;
	}


	/**
	 * Return the value associated with the column: ROOMFAMILYDESC
	 */
	public java.lang.String getRoomfamilydesc () {
		return _roomfamilydesc;
	}

	/**
	 * Set the value related to the column: ROOMFAMILYDESC
	 * @param _roomfamilydesc the ROOMFAMILYDESC value
	 */
	public void setRoomfamilydesc (java.lang.String _roomfamilydesc) {
		this._roomfamilydesc = _roomfamilydesc;
	}


	/**
	 * Return the value associated with the column: RESTRICTIONS
	 */
	public java.lang.String getRestrictions () {
		return _restrictions;
	}

	/**
	 * Set the value related to the column: RESTRICTIONS
	 * @param _restrictions the RESTRICTIONS value
	 */
	public void setRestrictions (java.lang.String _restrictions) {
		this._restrictions = _restrictions;
	}


	/**
	 * Return the value associated with the column: RECREATIONFEE
	 */
	public java.math.BigDecimal getRecreationfee () {
		return _recreationfee;
	}

	/**
	 * Set the value related to the column: RECREATIONFEE
	 * @param _recreationfee the RECREATIONFEE value
	 */
	public void setRecreationfee (java.math.BigDecimal _recreationfee) {
		this._recreationfee = _recreationfee;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER1NAME
	 */
	public java.lang.String getRoomother1name () {
		return _roomother1name;
	}

	/**
	 * Set the value related to the column: ROOMOTHER1NAME
	 * @param _roomother1name the ROOMOTHER1NAME value
	 */
	public void setRoomother1name (java.lang.String _roomother1name) {
		this._roomother1name = _roomother1name;
	}


	/**
	 * Return the value associated with the column: PHOTOCOUNT
	 */
	public java.math.BigDecimal getPhotocount () {
		return _photocount;
	}

	/**
	 * Set the value related to the column: PHOTOCOUNT
	 * @param _photocount the PHOTOCOUNT value
	 */
	public void setPhotocount (java.math.BigDecimal _photocount) {
		this._photocount = _photocount;
	}


	/**
	 * Return the value associated with the column: ASSOCFEEPAID
	 */
	public java.lang.String getAssocfeepaid () {
		return _assocfeepaid;
	}

	/**
	 * Set the value related to the column: ASSOCFEEPAID
	 * @param _assocfeepaid the ASSOCFEEPAID value
	 */
	public void setAssocfeepaid (java.lang.String _assocfeepaid) {
		this._assocfeepaid = _assocfeepaid;
	}


	/**
	 * Return the value associated with the column: HOMEOWNERSASSOC
	 */
	public java.lang.String getHomeownersassoc () {
		return _homeownersassoc;
	}

	/**
	 * Set the value related to the column: HOMEOWNERSASSOC
	 * @param _homeownersassoc the HOMEOWNERSASSOC value
	 */
	public void setHomeownersassoc (java.lang.String _homeownersassoc) {
		this._homeownersassoc = _homeownersassoc;
	}


	/**
	 * Return the value associated with the column: HEATSRC
	 */
	public java.lang.String getHeatsrc () {
		return _heatsrc;
	}

	/**
	 * Set the value related to the column: HEATSRC
	 * @param _heatsrc the HEATSRC value
	 */
	public void setHeatsrc (java.lang.String _heatsrc) {
		this._heatsrc = _heatsrc;
	}


	/**
	 * Return the value associated with the column: ROOMDININGDIM
	 */
	public java.lang.String getRoomdiningdim () {
		return _roomdiningdim;
	}

	/**
	 * Set the value related to the column: ROOMDININGDIM
	 * @param _roomdiningdim the ROOMDININGDIM value
	 */
	public void setRoomdiningdim (java.lang.String _roomdiningdim) {
		this._roomdiningdim = _roomdiningdim;
	}


	/**
	 * Return the value associated with the column: ROOMDENDESC
	 */
	public java.lang.String getRoomdendesc () {
		return _roomdendesc;
	}

	/**
	 * Set the value related to the column: ROOMDENDESC
	 * @param _roomdendesc the ROOMDENDESC value
	 */
	public void setRoomdendesc (java.lang.String _roomdendesc) {
		this._roomdendesc = _roomdendesc;
	}


	/**
	 * Return the value associated with the column: MAPPAGE
	 */
	public java.math.BigDecimal getMappage () {
		return _mappage;
	}

	/**
	 * Set the value related to the column: MAPPAGE
	 * @param _mappage the MAPPAGE value
	 */
	public void setMappage (java.math.BigDecimal _mappage) {
		this._mappage = _mappage;
	}


	/**
	 * Return the value associated with the column: LOTDESC
	 */
	public java.lang.String getLotdesc () {
		return _lotdesc;
	}

	/**
	 * Set the value related to the column: LOTDESC
	 * @param _lotdesc the LOTDESC value
	 */
	public void setLotdesc (java.lang.String _lotdesc) {
		this._lotdesc = _lotdesc;
	}


	/**
	 * Return the value associated with the column: COUNTY
	 */
	public java.lang.String getCounty () {
		return _county;
	}

	/**
	 * Set the value related to the column: COUNTY
	 * @param _county the COUNTY value
	 */
	public void setCounty (java.lang.String _county) {
		this._county = _county;
	}


	/**
	 * Return the value associated with the column: BED3DESC
	 */
	public java.lang.String getBed3desc () {
		return _bed3desc;
	}

	/**
	 * Set the value related to the column: BED3DESC
	 * @param _bed3desc the BED3DESC value
	 */
	public void setBed3desc (java.lang.String _bed3desc) {
		this._bed3desc = _bed3desc;
	}


	/**
	 * Return the value associated with the column: CITY
	 */
	public java.lang.String getCity () {
		return _city;
	}

	/**
	 * Set the value related to the column: CITY
	 * @param _city the CITY value
	 */
	public void setCity (java.lang.String _city) {
		this._city = _city;
	}


	/**
	 * Return the value associated with the column: MONTHWATER
	 */
	public java.math.BigDecimal getMonthwater () {
		return _monthwater;
	}

	/**
	 * Set the value related to the column: MONTHWATER
	 * @param _monthwater the MONTHWATER value
	 */
	public void setMonthwater (java.math.BigDecimal _monthwater) {
		this._monthwater = _monthwater;
	}


	/**
	 * Return the value associated with the column: BED3LEVEL
	 */
	public java.lang.String getBed3level () {
		return _bed3level;
	}

	/**
	 * Set the value related to the column: BED3LEVEL
	 * @param _bed3level the BED3LEVEL value
	 */
	public void setBed3level (java.lang.String _bed3level) {
		this._bed3level = _bed3level;
	}


	/**
	 * Return the value associated with the column: LATITUDE
	 */
	public java.math.BigDecimal getLatitude () {
		return _latitude;
	}

	/**
	 * Set the value related to the column: LATITUDE
	 * @param _latitude the LATITUDE value
	 */
	public void setLatitude (java.math.BigDecimal _latitude) {
		this._latitude = _latitude;
	}


	/**
	 * Return the value associated with the column: SCHOOLDISTRICT
	 */
	public java.lang.String getSchooldistrict () {
		return _schooldistrict;
	}

	/**
	 * Set the value related to the column: SCHOOLDISTRICT
	 * @param _schooldistrict the SCHOOLDISTRICT value
	 */
	public void setSchooldistrict (java.lang.String _schooldistrict) {
		this._schooldistrict = _schooldistrict;
	}


	/**
	 * Return the value associated with the column: STREETNUMDISPLAY
	 */
	public java.lang.String getStreetnumdisplay () {
		return _streetnumdisplay;
	}

	/**
	 * Set the value related to the column: STREETNUMDISPLAY
	 * @param _streetnumdisplay the STREETNUMDISPLAY value
	 */
	public void setStreetnumdisplay (java.lang.String _streetnumdisplay) {
		this._streetnumdisplay = _streetnumdisplay;
	}


	/**
	 * Return the value associated with the column: MAINTFEE
	 */
	public java.math.BigDecimal getMaintfee () {
		return _maintfee;
	}

	/**
	 * Set the value related to the column: MAINTFEE
	 * @param _maintfee the MAINTFEE value
	 */
	public void setMaintfee (java.math.BigDecimal _maintfee) {
		this._maintfee = _maintfee;
	}


	/**
	 * Return the value associated with the column: BATHSFULL
	 */
	public java.math.BigDecimal getBathsfull () {
		return _bathsfull;
	}

	/**
	 * Set the value related to the column: BATHSFULL
	 * @param _bathsfull the BATHSFULL value
	 */
	public void setBathsfull (java.math.BigDecimal _bathsfull) {
		this._bathsfull = _bathsfull;
	}


	/**
	 * Return the value associated with the column: BED4DIM
	 */
	public java.lang.String getBed4dim () {
		return _bed4dim;
	}

	/**
	 * Set the value related to the column: BED4DIM
	 * @param _bed4dim the BED4DIM value
	 */
	public void setBed4dim (java.lang.String _bed4dim) {
		this._bed4dim = _bed4dim;
	}


	/**
	 * Return the value associated with the column: PHOTODATE
	 */
	public java.util.Date getPhotodate () {
		return _photodate;
	}

	/**
	 * Set the value related to the column: PHOTODATE
	 * @param _photodate the PHOTODATE value
	 */
	public void setPhotodate (java.util.Date _photodate) {
		this._photodate = _photodate;
	}


	/**
	 * Return the value associated with the column: ROOMKITCHENLEVEL
	 */
	public java.lang.String getRoomkitchenlevel () {
		return _roomkitchenlevel;
	}

	/**
	 * Set the value related to the column: ROOMKITCHENLEVEL
	 * @param _roomkitchenlevel the ROOMKITCHENLEVEL value
	 */
	public void setRoomkitchenlevel (java.lang.String _roomkitchenlevel) {
		this._roomkitchenlevel = _roomkitchenlevel;
	}


	/**
	 * Return the value associated with the column: APPLIANCES
	 */
	public java.lang.String getAppliances () {
		return _appliances;
	}

	/**
	 * Set the value related to the column: APPLIANCES
	 * @param _appliances the APPLIANCES value
	 */
	public void setAppliances (java.lang.String _appliances) {
		this._appliances = _appliances;
	}


	/**
	 * Return the value associated with the column: LISTPRICE
	 */
	public java.math.BigDecimal getListprice () {
		return _listprice;
	}

	/**
	 * Set the value related to the column: LISTPRICE
	 * @param _listprice the LISTPRICE value
	 */
	public void setListprice (java.math.BigDecimal _listprice) {
		this._listprice = _listprice;
	}


	/**
	 * Return the value associated with the column: DAYSONMARKET
	 */
	public java.math.BigDecimal getDaysonmarket () {
		return _daysonmarket;
	}

	/**
	 * Set the value related to the column: DAYSONMARKET
	 * @param _daysonmarket the DAYSONMARKET value
	 */
	public void setDaysonmarket (java.math.BigDecimal _daysonmarket) {
		this._daysonmarket = _daysonmarket;
	}


	/**
	 * Return the value associated with the column: PUBLICTRANS
	 */
	public java.lang.String getPublictrans () {
		return _publictrans;
	}

	/**
	 * Set the value related to the column: PUBLICTRANS
	 * @param _publictrans the PUBLICTRANS value
	 */
	public void setPublictrans (java.lang.String _publictrans) {
		this._publictrans = _publictrans;
	}


	/**
	 * Return the value associated with the column: ROOMKITCHENDIM
	 */
	public java.lang.String getRoomkitchendim () {
		return _roomkitchendim;
	}

	/**
	 * Set the value related to the column: ROOMKITCHENDIM
	 * @param _roomkitchendim the ROOMKITCHENDIM value
	 */
	public void setRoomkitchendim (java.lang.String _roomkitchendim) {
		this._roomkitchendim = _roomkitchendim;
	}


	/**
	 * Return the value associated with the column: LOTRENT
	 */
	public java.lang.String getLotrent () {
		return _lotrent;
	}

	/**
	 * Set the value related to the column: LOTRENT
	 * @param _lotrent the LOTRENT value
	 */
	public void setLotrent (java.lang.String _lotrent) {
		this._lotrent = _lotrent;
	}


	/**
	 * Return the value associated with the column: SCHOOLHIGH
	 */
	public java.lang.String getSchoolhigh () {
		return _schoolhigh;
	}

	/**
	 * Set the value related to the column: SCHOOLHIGH
	 * @param _schoolhigh the SCHOOLHIGH value
	 */
	public void setSchoolhigh (java.lang.String _schoolhigh) {
		this._schoolhigh = _schoolhigh;
	}


	/**
	 * Return the value associated with the column: STREETNAME
	 */
	public java.lang.String getStreetname () {
		return _streetname;
	}

	/**
	 * Set the value related to the column: STREETNAME
	 * @param _streetname the STREETNAME value
	 */
	public void setStreetname (java.lang.String _streetname) {
		this._streetname = _streetname;
	}


	/**
	 * Return the value associated with the column: SELLERPOINTS
	 */
	public java.math.BigDecimal getSellerpoints () {
		return _sellerpoints;
	}

	/**
	 * Set the value related to the column: SELLERPOINTS
	 * @param _sellerpoints the SELLERPOINTS value
	 */
	public void setSellerpoints (java.math.BigDecimal _sellerpoints) {
		this._sellerpoints = _sellerpoints;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER3LEVEL
	 */
	public java.lang.String getRoomother3level () {
		return _roomother3level;
	}

	/**
	 * Set the value related to the column: ROOMOTHER3LEVEL
	 * @param _roomother3level the ROOMOTHER3LEVEL value
	 */
	public void setRoomother3level (java.lang.String _roomother3level) {
		this._roomother3level = _roomother3level;
	}


	/**
	 * Return the value associated with the column: MLSTYPE
	 */
	public java.lang.String getMlstype () {
		return _mlstype;
	}

	/**
	 * Set the value related to the column: MLSTYPE
	 * @param _mlstype the MLSTYPE value
	 */
	public void setMlstype (java.lang.String _mlstype) {
		this._mlstype = _mlstype;
	}


	/**
	 * Return the value associated with the column: TAXAMOUNT
	 */
	public java.math.BigDecimal getTaxamount () {
		return _taxamount;
	}

	/**
	 * Set the value related to the column: TAXAMOUNT
	 * @param _taxamount the TAXAMOUNT value
	 */
	public void setTaxamount (java.math.BigDecimal _taxamount) {
		this._taxamount = _taxamount;
	}


	/**
	 * Return the value associated with the column: BED2DIM
	 */
	public java.lang.String getBed2dim () {
		return _bed2dim;
	}

	/**
	 * Set the value related to the column: BED2DIM
	 * @param _bed2dim the BED2DIM value
	 */
	public void setBed2dim (java.lang.String _bed2dim) {
		this._bed2dim = _bed2dim;
	}


	/**
	 * Return the value associated with the column: BED5DIM
	 */
	public java.lang.String getBed5dim () {
		return _bed5dim;
	}

	/**
	 * Set the value related to the column: BED5DIM
	 * @param _bed5dim the BED5DIM value
	 */
	public void setBed5dim (java.lang.String _bed5dim) {
		this._bed5dim = _bed5dim;
	}


	/**
	 * Return the value associated with the column: ROOMFAMILYDIM
	 */
	public java.lang.String getRoomfamilydim () {
		return _roomfamilydim;
	}

	/**
	 * Set the value related to the column: ROOMFAMILYDIM
	 * @param _roomfamilydim the ROOMFAMILYDIM value
	 */
	public void setRoomfamilydim (java.lang.String _roomfamilydim) {
		this._roomfamilydim = _roomfamilydim;
	}


	/**
	 * Return the value associated with the column: ASSOCFEE
	 */
	public java.math.BigDecimal getAssocfee () {
		return _assocfee;
	}

	/**
	 * Set the value related to the column: ASSOCFEE
	 * @param _assocfee the ASSOCFEE value
	 */
	public void setAssocfee (java.math.BigDecimal _assocfee) {
		this._assocfee = _assocfee;
	}


	/**
	 * Return the value associated with the column: LOTNUM
	 */
	public java.lang.String getLotnum () {
		return _lotnum;
	}

	/**
	 * Set the value related to the column: LOTNUM
	 * @param _lotnum the LOTNUM value
	 */
	public void setLotnum (java.lang.String _lotnum) {
		this._lotnum = _lotnum;
	}


	/**
	 * Return the value associated with the column: SALESPRICE
	 */
	public java.math.BigDecimal getSalesprice () {
		return _salesprice;
	}

	/**
	 * Set the value related to the column: SALESPRICE
	 * @param _salesprice the SALESPRICE value
	 */
	public void setSalesprice (java.math.BigDecimal _salesprice) {
		this._salesprice = _salesprice;
	}


	/**
	 * Return the value associated with the column: LISTDATE
	 */
	public java.util.Date getListdate () {
		return _listdate;
	}

	/**
	 * Set the value related to the column: LISTDATE
	 * @param _listdate the LISTDATE value
	 */
	public void setListdate (java.util.Date _listdate) {
		this._listdate = _listdate;
	}


	/**
	 * Return the value associated with the column: ZONING
	 */
	public java.lang.String getZoning () {
		return _zoning;
	}

	/**
	 * Set the value related to the column: ZONING
	 * @param _zoning the ZONING value
	 */
	public void setZoning (java.lang.String _zoning) {
		this._zoning = _zoning;
	}


	/**
	 * Return the value associated with the column: PROPSUBTYPE
	 */
	public java.lang.String getPropsubtype () {
		return _propsubtype;
	}

	/**
	 * Set the value related to the column: PROPSUBTYPE
	 * @param _propsubtype the PROPSUBTYPE value
	 */
	public void setPropsubtype (java.lang.String _propsubtype) {
		this._propsubtype = _propsubtype;
	}


	/**
	 * Return the value associated with the column: AGENTLIST
	 */
	public java.lang.String getAgentlisting () {
		return _agentlisting;
	}

	/**
	 * Set the value related to the column: AGENTLIST
	 * @param _agentlisting the AGENTLIST value
	 */
	public void setAgentlisting (java.lang.String _agentlisting) {
		this._agentlisting = _agentlisting;
	}


	/**
	 * Return the value associated with the column: CLOSEDDATE
	 */
	public java.util.Date getCloseddate () {
		return _closeddate;
	}

	/**
	 * Set the value related to the column: CLOSEDDATE
	 * @param _closeddate the CLOSEDDATE value
	 */
	public void setCloseddate (java.util.Date _closeddate) {
		this._closeddate = _closeddate;
	}


	/**
	 * Return the value associated with the column: FENCE
	 */
	public java.lang.String getFence () {
		return _fence;
	}

	/**
	 * Set the value related to the column: FENCE
	 * @param _fence the FENCE value
	 */
	public void setFence (java.lang.String _fence) {
		this._fence = _fence;
	}


	/**
	 * Return the value associated with the column: CONTINGENCY
	 */
	public java.lang.String getContingency () {
		return _contingency;
	}

	/**
	 * Set the value related to the column: CONTINGENCY
	 * @param _contingency the CONTINGENCY value
	 */
	public void setContingency (java.lang.String _contingency) {
		this._contingency = _contingency;
	}


	/**
	 * Return the value associated with the column: LONGITUDE
	 */
	public java.math.BigDecimal getLongitude () {
		return _longitude;
	}

	/**
	 * Set the value related to the column: LONGITUDE
	 * @param _longitude the LONGITUDE value
	 */
	public void setLongitude (java.math.BigDecimal _longitude) {
		this._longitude = _longitude;
	}


	/**
	 * Return the value associated with the column: STREETDIR
	 */
	public java.lang.String getStreetdir () {
		return _streetdir;
	}

	/**
	 * Set the value related to the column: STREETDIR
	 * @param _streetdir the STREETDIR value
	 */
	public void setStreetdir (java.lang.String _streetdir) {
		this._streetdir = _streetdir;
	}


	/**
	 * Return the value associated with the column: SELLING_AGENT
	 */
	public java.lang.Integer getSellingAgent () {
		return _sellingAgent;
	}

	/**
	 * Set the value related to the column: SELLING_AGENT
	 * @param _sellingAgent the SELLING_AGENT value
	 */
	public void setSellingAgent (java.lang.Integer _sellingAgent) {
		this._sellingAgent = _sellingAgent;
	}


	/**
	 * Return the value associated with the column: MLSCROSSREF
	 */
	public java.lang.String getMlscrossref () {
		return _mlscrossref;
	}

	/**
	 * Set the value related to the column: MLSCROSSREF
	 * @param _mlscrossref the MLSCROSSREF value
	 */
	public void setMlscrossref (java.lang.String _mlscrossref) {
		this._mlscrossref = _mlscrossref;
	}


	/**
	 * Return the value associated with the column: CLOSEDBY
	 */
	public java.lang.String getClosedby () {
		return _closedby;
	}

	/**
	 * Set the value related to the column: CLOSEDBY
	 * @param _closedby the CLOSEDBY value
	 */
	public void setClosedby (java.lang.String _closedby) {
		this._closedby = _closedby;
	}


	/**
	 * Return the value associated with the column: MONTHGAS
	 */
	public java.math.BigDecimal getMonthgas () {
		return _monthgas;
	}

	/**
	 * Set the value related to the column: MONTHGAS
	 * @param _monthgas the MONTHGAS value
	 */
	public void setMonthgas (java.math.BigDecimal _monthgas) {
		this._monthgas = _monthgas;
	}


	/**
	 * Return the value associated with the column: FINANCECODE
	 */
	public java.lang.String getFinancecode () {
		return _financecode;
	}

	/**
	 * Set the value related to the column: FINANCECODE
	 * @param _financecode the FINANCECODE value
	 */
	public void setFinancecode (java.lang.String _financecode) {
		this._financecode = _financecode;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER3DESC
	 */
	public java.lang.String getRoomother3desc () {
		return _roomother3desc;
	}

	/**
	 * Set the value related to the column: ROOMOTHER3DESC
	 * @param _roomother3desc the ROOMOTHER3DESC value
	 */
	public void setRoomother3desc (java.lang.String _roomother3desc) {
		this._roomother3desc = _roomother3desc;
	}


	/**
	 * Return the value associated with the column: STYLE
	 */
	public java.lang.String getStyle () {
		return _style;
	}

	/**
	 * Set the value related to the column: STYLE
	 * @param _style the STYLE value
	 */
	public void setStyle (java.lang.String _style) {
		this._style = _style;
	}


	/**
	 * Return the value associated with the column: UID
	 */
	public java.lang.Long getUid () {
		return _uid;
	}

	/**
	 * Set the value related to the column: UID
	 * @param _uid the UID value
	 */
	public void setUid (java.lang.Long _uid) {
		this._uid = _uid;
	}


	/**
	 * Return the value associated with the column: UNITFLOORNUM
	 */
	public java.lang.String getUnitfloornum () {
		return _unitfloornum;
	}

	/**
	 * Set the value related to the column: UNITFLOORNUM
	 * @param _unitfloornum the UNITFLOORNUM value
	 */
	public void setUnitfloornum (java.lang.String _unitfloornum) {
		this._unitfloornum = _unitfloornum;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER3NAME
	 */
	public java.lang.String getRoomother3name () {
		return _roomother3name;
	}

	/**
	 * Set the value related to the column: ROOMOTHER3NAME
	 * @param _roomother3name the ROOMOTHER3NAME value
	 */
	public void setRoomother3name (java.lang.String _roomother3name) {
		this._roomother3name = _roomother3name;
	}


	/**
	 * Return the value associated with the column: POSSESSION
	 */
	public java.lang.String getPossession () {
		return _possession;
	}

	/**
	 * Set the value related to the column: POSSESSION
	 * @param _possession the POSSESSION value
	 */
	public void setPossession (java.lang.String _possession) {
		this._possession = _possession;
	}


	/**
	 * Return the value associated with the column: BATHSHALF
	 */
	public java.math.BigDecimal getBathshalf () {
		return _bathshalf;
	}

	/**
	 * Set the value related to the column: BATHSHALF
	 * @param _bathshalf the BATHSHALF value
	 */
	public void setBathshalf (java.math.BigDecimal _bathshalf) {
		this._bathshalf = _bathshalf;
	}


	/**
	 * Return the value associated with the column: BED2LEVEL
	 */
	public java.lang.String getBed2level () {
		return _bed2level;
	}

	/**
	 * Set the value related to the column: BED2LEVEL
	 * @param _bed2level the BED2LEVEL value
	 */
	public void setBed2level (java.lang.String _bed2level) {
		this._bed2level = _bed2level;
	}


	/**
	 * Return the value associated with the column: PARKINGCOVERED
	 */
	public java.math.BigDecimal getParkingcovered () {
		return _parkingcovered;
	}

	/**
	 * Set the value related to the column: PARKINGCOVERED
	 * @param _parkingcovered the PARKINGCOVERED value
	 */
	public void setParkingcovered (java.math.BigDecimal _parkingcovered) {
		this._parkingcovered = _parkingcovered;
	}


	/**
	 * Return the value associated with the column: HANDICAP
	 */
	public java.lang.String getHandicap () {
		return _handicap;
	}

	/**
	 * Set the value related to the column: HANDICAP
	 * @param _handicap the HANDICAP value
	 */
	public void setHandicap (java.lang.String _handicap) {
		this._handicap = _handicap;
	}


	/**
	 * Return the value associated with the column: ROOMFAMILYLEVEL
	 */
	public java.lang.String getRoomfamilylevel () {
		return _roomfamilylevel;
	}

	/**
	 * Set the value related to the column: ROOMFAMILYLEVEL
	 * @param _roomfamilylevel the ROOMFAMILYLEVEL value
	 */
	public void setRoomfamilylevel (java.lang.String _roomfamilylevel) {
		this._roomfamilylevel = _roomfamilylevel;
	}


	/**
	 * Return the value associated with the column: LOCKBOXDESC
	 */
	public java.lang.String getLockboxdesc () {
		return _lockboxdesc;
	}

	/**
	 * Set the value related to the column: LOCKBOXDESC
	 * @param _lockboxdesc the LOCKBOXDESC value
	 */
	public void setLockboxdesc (java.lang.String _lockboxdesc) {
		this._lockboxdesc = _lockboxdesc;
	}


	/**
	 * Return the value associated with the column: OFFICESELL
	 */
	public java.lang.String getOfficesell () {
		return _officesell;
	}

	/**
	 * Set the value related to the column: OFFICESELL
	 * @param _officesell the OFFICESELL value
	 */
	public void setOfficesell (java.lang.String _officesell) {
		this._officesell = _officesell;
	}


	/**
	 * Return the value associated with the column: SQFTUNFINISHED
	 */
	public java.math.BigDecimal getSqftunfinished () {
		return _sqftunfinished;
	}

	/**
	 * Set the value related to the column: SQFTUNFINISHED
	 * @param _sqftunfinished the SQFTUNFINISHED value
	 */
	public void setSqftunfinished (java.math.BigDecimal _sqftunfinished) {
		this._sqftunfinished = _sqftunfinished;
	}


	/**
	 * Return the value associated with the column: SQFTFINISHED
	 */
	public java.math.BigDecimal getSqftfinished () {
		return _sqftfinished;
	}

	/**
	 * Set the value related to the column: SQFTFINISHED
	 * @param _sqftfinished the SQFTFINISHED value
	 */
	public void setSqftfinished (java.math.BigDecimal _sqftfinished) {
		this._sqftfinished = _sqftfinished;
	}


	/**
	 * Return the value associated with the column: MAINTFEEINCLUDES
	 */
	public java.lang.String getMaintfeeincludes () {
		return _maintfeeincludes;
	}

	/**
	 * Set the value related to the column: MAINTFEEINCLUDES
	 * @param _maintfeeincludes the MAINTFEEINCLUDES value
	 */
	public void setMaintfeeincludes (java.lang.String _maintfeeincludes) {
		this._maintfeeincludes = _maintfeeincludes;
	}


	/**
	 * Return the value associated with the column: BED4DESC
	 */
	public java.lang.String getBed4desc () {
		return _bed4desc;
	}

	/**
	 * Set the value related to the column: BED4DESC
	 * @param _bed4desc the BED4DESC value
	 */
	public void setBed4desc (java.lang.String _bed4desc) {
		this._bed4desc = _bed4desc;
	}


	/**
	 * Return the value associated with the column: LOTDIM
	 */
	public java.lang.String getLotdim () {
		return _lotdim;
	}

	/**
	 * Set the value related to the column: LOTDIM
	 * @param _lotdim the LOTDIM value
	 */
	public void setLotdim (java.lang.String _lotdim) {
		this._lotdim = _lotdim;
	}


	/**
	 * Return the value associated with the column: OFFMARKETDATE
	 */
	public java.util.Date getOffmarketdate () {
		return _offmarketdate;
	}

	/**
	 * Set the value related to the column: OFFMARKETDATE
	 * @param _offmarketdate the OFFMARKETDATE value
	 */
	public void setOffmarketdate (java.util.Date _offmarketdate) {
		this._offmarketdate = _offmarketdate;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER
	 */
	public java.lang.String getRoomother () {
		return _roomother;
	}

	/**
	 * Set the value related to the column: ROOMOTHER
	 * @param _roomother the ROOMOTHER value
	 */
	public void setRoomother (java.lang.String _roomother) {
		this._roomother = _roomother;
	}


	/**
	 * Return the value associated with the column: ROOMLIVINGDIM
	 */
	public java.lang.String getRoomlivingdim () {
		return _roomlivingdim;
	}

	/**
	 * Set the value related to the column: ROOMLIVINGDIM
	 * @param _roomlivingdim the ROOMLIVINGDIM value
	 */
	public void setRoomlivingdim (java.lang.String _roomlivingdim) {
		this._roomlivingdim = _roomlivingdim;
	}


	/**
	 * Return the value associated with the column: BED3DIM
	 */
	public java.lang.String getBed3dim () {
		return _bed3dim;
	}

	/**
	 * Set the value related to the column: BED3DIM
	 * @param _bed3dim the BED3DIM value
	 */
	public void setBed3dim (java.lang.String _bed3dim) {
		this._bed3dim = _bed3dim;
	}


	/**
	 * Return the value associated with the column: GARAGEDESC
	 */
	public java.lang.String getGaragedesc () {
		return _garagedesc;
	}

	/**
	 * Set the value related to the column: GARAGEDESC
	 * @param _garagedesc the GARAGEDESC value
	 */
	public void setGaragedesc (java.lang.String _garagedesc) {
		this._garagedesc = _garagedesc;
	}


	/**
	 * Return the value associated with the column: HEATSYSTEM
	 */
	public java.lang.String getHeatsystem () {
		return _heatsystem;
	}

	/**
	 * Set the value related to the column: HEATSYSTEM
	 * @param _heatsystem the HEATSYSTEM value
	 */
	public void setHeatsystem (java.lang.String _heatsystem) {
		this._heatsystem = _heatsystem;
	}


	/**
	 * Return the value associated with the column: PHOTOCODE
	 */
	public java.lang.String getPhotocode () {
		return _photocode;
	}

	/**
	 * Set the value related to the column: PHOTOCODE
	 * @param _photocode the PHOTOCODE value
	 */
	public void setPhotocode (java.lang.String _photocode) {
		this._photocode = _photocode;
	}


	/**
	 * Return the value associated with the column: WITHDRAWNDATE
	 */
	public java.util.Date getWithdrawndate () {
		return _withdrawndate;
	}

	/**
	 * Set the value related to the column: WITHDRAWNDATE
	 * @param _withdrawndate the WITHDRAWNDATE value
	 */
	public void setWithdrawndate (java.util.Date _withdrawndate) {
		this._withdrawndate = _withdrawndate;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER2LEVEL
	 */
	public java.lang.String getRoomother2level () {
		return _roomother2level;
	}

	/**
	 * Set the value related to the column: ROOMOTHER2LEVEL
	 * @param _roomother2level the ROOMOTHER2LEVEL value
	 */
	public void setRoomother2level (java.lang.String _roomother2level) {
		this._roomother2level = _roomother2level;
	}


	/**
	 * Return the value associated with the column: MODIFIED
	 */
	public java.util.Date getModified () {
		return _modified;
	}

	/**
	 * Set the value related to the column: MODIFIED
	 * @param _modified the MODIFIED value
	 */
	public void setModified (java.util.Date _modified) {
		this._modified = _modified;
	}


	/**
	 * Return the value associated with the column: EXTERIOR
	 */
	public java.lang.String getExterior () {
		return _exterior;
	}

	/**
	 * Set the value related to the column: EXTERIOR
	 * @param _exterior the EXTERIOR value
	 */
	public void setExterior (java.lang.String _exterior) {
		this._exterior = _exterior;
	}


	/**
	 * Return the value associated with the column: LISTSTATUS
	 */
	public java.lang.String getListstatus () {
		return _liststatus;
	}

	/**
	 * Set the value related to the column: LISTSTATUS
	 * @param _liststatus the LISTSTATUS value
	 */
	public void setListstatus (java.lang.String _liststatus) {
		this._liststatus = _liststatus;
	}


	/**
	 * Return the value associated with the column: ROOMDININGDESC
	 */
	public java.lang.String getRoomdiningdesc () {
		return _roomdiningdesc;
	}

	/**
	 * Set the value related to the column: ROOMDININGDESC
	 * @param _roomdiningdesc the ROOMDININGDESC value
	 */
	public void setRoomdiningdesc (java.lang.String _roomdiningdesc) {
		this._roomdiningdesc = _roomdiningdesc;
	}


	/**
	 * Return the value associated with the column: FINANCEACCEPTABLE
	 */
	public java.lang.String getFinanceacceptable () {
		return _financeacceptable;
	}

	/**
	 * Set the value related to the column: FINANCEACCEPTABLE
	 * @param _financeacceptable the FINANCEACCEPTABLE value
	 */
	public void setFinanceacceptable (java.lang.String _financeacceptable) {
		this._financeacceptable = _financeacceptable;
	}


	/**
	 * Return the value associated with the column: AREA
	 */
	public java.math.BigDecimal getArea () {
		return _area;
	}

	/**
	 * Set the value related to the column: AREA
	 * @param _area the AREA value
	 */
	public void setArea (java.math.BigDecimal _area) {
		this._area = _area;
	}


	/**
	 * Return the value associated with the column: COOLSYSTEM
	 */
	public java.lang.String getCoolsystem () {
		return _coolsystem;
	}

	/**
	 * Set the value related to the column: COOLSYSTEM
	 * @param _coolsystem the COOLSYSTEM value
	 */
	public void setCoolsystem (java.lang.String _coolsystem) {
		this._coolsystem = _coolsystem;
	}


	/**
	 * Return the value associated with the column: LISTING_AGENT
	 */
	public java.lang.Integer getListingAgent () {
		return _listingAgent;
	}

	/**
	 * Set the value related to the column: LISTING_AGENT
	 * @param _listingAgent the LISTING_AGENT value
	 */
	public void setListingAgent (java.lang.Integer _listingAgent) {
		this._listingAgent = _listingAgent;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER2DIM
	 */
	public java.lang.String getRoomother2dim () {
		return _roomother2dim;
	}

	/**
	 * Set the value related to the column: ROOMOTHER2DIM
	 * @param _roomother2dim the ROOMOTHER2DIM value
	 */
	public void setRoomother2dim (java.lang.String _roomother2dim) {
		this._roomother2dim = _roomother2dim;
	}


	/**
	 * Return the value associated with the column: AMENITIES
	 */
	public java.lang.String getAmenities () {
		return _amenities;
	}

	/**
	 * Set the value related to the column: AMENITIES
	 * @param _amenities the AMENITIES value
	 */
	public void setAmenities (java.lang.String _amenities) {
		this._amenities = _amenities;
	}


	/**
	 * Return the value associated with the column: COMPOTHER
	 */
	public java.lang.String getCompother () {
		return _compother;
	}

	/**
	 * Set the value related to the column: COMPOTHER
	 * @param _compother the COMPOTHER value
	 */
	public void setCompother (java.lang.String _compother) {
		this._compother = _compother;
	}


	/**
	 * Return the value associated with the column: MLSNUM_CRIS
	 */
	public java.lang.String getMlsnumCris () {
		return _mlsnumCris;
	}

	/**
	 * Set the value related to the column: MLSNUM_CRIS
	 * @param _mlsnumCris the MLSNUM_CRIS value
	 */
	public void setMlsnumCris (java.lang.String _mlsnumCris) {
		this._mlsnumCris = _mlsnumCris;
	}


	/**
	 * Return the value associated with the column: VIEWDESC
	 */
	public java.lang.String getViewdesc () {
		return _viewdesc;
	}

	/**
	 * Set the value related to the column: VIEWDESC
	 * @param _viewdesc the VIEWDESC value
	 */
	public void setViewdesc (java.lang.String _viewdesc) {
		this._viewdesc = _viewdesc;
	}


	/**
	 * Return the value associated with the column: LISTDATERECEIVED
	 */
	public java.util.Date getListdatereceived () {
		return _listdatereceived;
	}

	/**
	 * Set the value related to the column: LISTDATERECEIVED
	 * @param _listdatereceived the LISTDATERECEIVED value
	 */
	public void setListdatereceived (java.util.Date _listdatereceived) {
		this._listdatereceived = _listdatereceived;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER1LEVEL
	 */
	public java.lang.String getRoomother1level () {
		return _roomother1level;
	}

	/**
	 * Set the value related to the column: ROOMOTHER1LEVEL
	 * @param _roomother1level the ROOMOTHER1LEVEL value
	 */
	public void setRoomother1level (java.lang.String _roomother1level) {
		this._roomother1level = _roomother1level;
	}


	/**
	 * Return the value associated with the column: SIDING
	 */
	public java.lang.String getSiding () {
		return _siding;
	}

	/**
	 * Set the value related to the column: SIDING
	 * @param _siding the SIDING value
	 */
	public void setSiding (java.lang.String _siding) {
		this._siding = _siding;
	}


	/**
	 * Return the value associated with the column: YEARBUILT
	 */
	public java.math.BigDecimal getYearbuilt () {
		return _yearbuilt;
	}

	/**
	 * Set the value related to the column: YEARBUILT
	 * @param _yearbuilt the YEARBUILT value
	 */
	public void setYearbuilt (java.math.BigDecimal _yearbuilt) {
		this._yearbuilt = _yearbuilt;
	}


	/**
	 * Return the value associated with the column: BED5LEVEL
	 */
	public java.lang.String getBed5level () {
		return _bed5level;
	}

	/**
	 * Set the value related to the column: BED5LEVEL
	 * @param _bed5level the BED5LEVEL value
	 */
	public void setBed5level (java.lang.String _bed5level) {
		this._bed5level = _bed5level;
	}


	/**
	 * Return the value associated with the column: BEDS
	 */
	public java.math.BigDecimal getBeds () {
		return _beds;
	}

	/**
	 * Set the value related to the column: BEDS
	 * @param _beds the BEDS value
	 */
	public void setBeds (java.math.BigDecimal _beds) {
		this._beds = _beds;
	}


	/**
	 * Return the value associated with the column: ROOMMASTERBEDLEVEL
	 */
	public java.lang.String getRoommasterbedlevel () {
		return _roommasterbedlevel;
	}

	/**
	 * Set the value related to the column: ROOMMASTERBEDLEVEL
	 * @param _roommasterbedlevel the ROOMMASTERBEDLEVEL value
	 */
	public void setRoommasterbedlevel (java.lang.String _roommasterbedlevel) {
		this._roommasterbedlevel = _roommasterbedlevel;
	}


	/**
	 * Return the value associated with the column: LISTPRICEORIG
	 */
	public java.math.BigDecimal getListpriceorig () {
		return _listpriceorig;
	}

	/**
	 * Set the value related to the column: LISTPRICEORIG
	 * @param _listpriceorig the LISTPRICEORIG value
	 */
	public void setListpriceorig (java.math.BigDecimal _listpriceorig) {
		this._listpriceorig = _listpriceorig;
	}


	/**
	 * Return the value associated with the column: SUBDIVISION
	 */
	public java.lang.String getSubdivision () {
		return _subdivision;
	}

	/**
	 * Set the value related to the column: SUBDIVISION
	 * @param _subdivision the SUBDIVISION value
	 */
	public void setSubdivision (java.lang.String _subdivision) {
		this._subdivision = _subdivision;
	}


	/**
	 * Return the value associated with the column: WARRANTY
	 */
	public java.lang.String getWarranty () {
		return _warranty;
	}

	/**
	 * Set the value related to the column: WARRANTY
	 * @param _warranty the WARRANTY value
	 */
	public void setWarranty (java.lang.String _warranty) {
		this._warranty = _warranty;
	}


	/**
	 * Return the value associated with the column: WATER
	 */
	public java.lang.String getWater () {
		return _water;
	}

	/**
	 * Set the value related to the column: WATER
	 * @param _water the WATER value
	 */
	public void setWater (java.lang.String _water) {
		this._water = _water;
	}


	/**
	 * Return the value associated with the column: ROOMLIVINGDESC
	 */
	public java.lang.String getRoomlivingdesc () {
		return _roomlivingdesc;
	}

	/**
	 * Set the value related to the column: ROOMLIVINGDESC
	 * @param _roomlivingdesc the ROOMLIVINGDESC value
	 */
	public void setRoomlivingdesc (java.lang.String _roomlivingdesc) {
		this._roomlivingdesc = _roomlivingdesc;
	}


	/**
	 * Return the value associated with the column: AUCTION
	 */
	public java.lang.String getAuction () {
		return _auction;
	}

	/**
	 * Set the value related to the column: AUCTION
	 * @param _auction the AUCTION value
	 */
	public void setAuction (java.lang.String _auction) {
		this._auction = _auction;
	}


	/**
	 * Return the value associated with the column: ROOMLIVINGLEVEL
	 */
	public java.lang.String getRoomlivinglevel () {
		return _roomlivinglevel;
	}

	/**
	 * Set the value related to the column: ROOMLIVINGLEVEL
	 * @param _roomlivinglevel the ROOMLIVINGLEVEL value
	 */
	public void setRoomlivinglevel (java.lang.String _roomlivinglevel) {
		this._roomlivinglevel = _roomlivinglevel;
	}


	/**
	 * Return the value associated with the column: BED2DESC
	 */
	public java.lang.String getBed2desc () {
		return _bed2desc;
	}

	/**
	 * Set the value related to the column: BED2DESC
	 * @param _bed2desc the BED2DESC value
	 */
	public void setBed2desc (java.lang.String _bed2desc) {
		this._bed2desc = _bed2desc;
	}


	/**
	 * Return the value associated with the column: INTERNETLIST
	 */
	public java.lang.String getInternetlist () {
		return _internetlist;
	}

	/**
	 * Set the value related to the column: INTERNETLIST
	 * @param _internetlist the INTERNETLIST value
	 */
	public void setInternetlist (java.lang.String _internetlist) {
		this._internetlist = _internetlist;
	}


	/**
	 * Return the value associated with the column: ZIPCODE
	 */
	public java.math.BigDecimal getZipcode () {
		return _zipcode;
	}

	/**
	 * Set the value related to the column: ZIPCODE
	 * @param _zipcode the ZIPCODE value
	 */
	public void setZipcode (java.math.BigDecimal _zipcode) {
		this._zipcode = _zipcode;
	}


	/**
	 * Return the value associated with the column: AGENTSELL
	 */
	public java.lang.String getAgentsell () {
		return _agentsell;
	}

	/**
	 * Set the value related to the column: AGENTSELL
	 * @param _agentsell the AGENTSELL value
	 */
	public void setAgentsell (java.lang.String _agentsell) {
		this._agentsell = _agentsell;
	}


	/**
	 * Return the value associated with the column: TAXPARCEL
	 */
	public java.lang.String getTaxparcel () {
		return _taxparcel;
	}

	/**
	 * Set the value related to the column: TAXPARCEL
	 * @param _taxparcel the TAXPARCEL value
	 */
	public void setTaxparcel (java.lang.String _taxparcel) {
		this._taxparcel = _taxparcel;
	}


	/**
	 * Return the value associated with the column: TEMPOFFMARKETDATE
	 */
	public java.util.Date getTempoffmarketdate () {
		return _tempoffmarketdate;
	}

	/**
	 * Set the value related to the column: TEMPOFFMARKETDATE
	 * @param _tempoffmarketdate the TEMPOFFMARKETDATE value
	 */
	public void setTempoffmarketdate (java.util.Date _tempoffmarketdate) {
		this._tempoffmarketdate = _tempoffmarketdate;
	}


	/**
	 * Return the value associated with the column: REMARKS
	 */
	public java.lang.String getRemarks () {
		return _remarks;
	}

	/**
	 * Set the value related to the column: REMARKS
	 * @param _remarks the REMARKS value
	 */
	public void setRemarks (java.lang.String _remarks) {
		this._remarks = _remarks;
	}


	/**
	 * Return the value associated with the column: OWNERAGENT
	 */
	public java.lang.String getOwneragent () {
		return _owneragent;
	}

	/**
	 * Set the value related to the column: OWNERAGENT
	 * @param _owneragent the OWNERAGENT value
	 */
	public void setOwneragent (java.lang.String _owneragent) {
		this._owneragent = _owneragent;
	}


	/**
	 * Return the value associated with the column: UIDPRP
	 */
	public java.lang.String getUidprp () {
		return _uidprp;
	}

	/**
	 * Set the value related to the column: UIDPRP
	 * @param _uidprp the UIDPRP value
	 */
	public void setUidprp (java.lang.String _uidprp) {
		this._uidprp = _uidprp;
	}


	/**
	 * Return the value associated with the column: FIREPLACES
	 */
	public java.lang.String getFireplaces () {
		return _fireplaces;
	}

	/**
	 * Set the value related to the column: FIREPLACES
	 * @param _fireplaces the FIREPLACES value
	 */
	public void setFireplaces (java.lang.String _fireplaces) {
		this._fireplaces = _fireplaces;
	}


	/**
	 * Return the value associated with the column: ROOMMASTERBEDDESC
	 */
	public java.lang.String getRoommasterbeddesc () {
		return _roommasterbeddesc;
	}

	/**
	 * Set the value related to the column: ROOMMASTERBEDDESC
	 * @param _roommasterbeddesc the ROOMMASTERBEDDESC value
	 */
	public void setRoommasterbeddesc (java.lang.String _roommasterbeddesc) {
		this._roommasterbeddesc = _roommasterbeddesc;
	}


	/**
	 * Return the value associated with the column: SCHOOLDISTRICT_DISPLAY
	 */
	public java.lang.String getSchooldistrictDisplay () {
		return _schooldistrictDisplay;
	}

	/**
	 * Set the value related to the column: SCHOOLDISTRICT_DISPLAY
	 * @param _schooldistrictDisplay the SCHOOLDISTRICT_DISPLAY value
	 */
	public void setSchooldistrictDisplay (java.lang.String _schooldistrictDisplay) {
		this._schooldistrictDisplay = _schooldistrictDisplay;
	}


	/**
	 * Return the value associated with the column: STORIES
	 */
	public java.math.BigDecimal getStories () {
		return _stories;
	}

	/**
	 * Set the value related to the column: STORIES
	 * @param _stories the STORIES value
	 */
	public void setStories (java.math.BigDecimal _stories) {
		this._stories = _stories;
	}


	/**
	 * Return the value associated with the column: ROOMDENDIM
	 */
	public java.lang.String getRoomdendim () {
		return _roomdendim;
	}

	/**
	 * Set the value related to the column: ROOMDENDIM
	 * @param _roomdendim the ROOMDENDIM value
	 */
	public void setRoomdendim (java.lang.String _roomdendim) {
		this._roomdendim = _roomdendim;
	}


	/**
	 * Return the value associated with the column: STREETNUM
	 */
	public java.lang.String getStreetnum () {
		return _streetnum;
	}

	/**
	 * Set the value related to the column: STREETNUM
	 * @param _streetnum the STREETNUM value
	 */
	public void setStreetnum (java.lang.String _streetnum) {
		this._streetnum = _streetnum;
	}


	/**
	 * Return the value associated with the column: ZIP4
	 */
	public java.math.BigDecimal getZip4 () {
		return _zip4;
	}

	/**
	 * Set the value related to the column: ZIP4
	 * @param _zip4 the ZIP4 value
	 */
	public void setZip4 (java.math.BigDecimal _zip4) {
		this._zip4 = _zip4;
	}


	/**
	 * Return the value associated with the column: SELLING_COMPANY
	 */
	public java.lang.Integer getSellingCompany () {
		return _sellingCompany;
	}

	/**
	 * Set the value related to the column: SELLING_COMPANY
	 * @param _sellingCompany the SELLING_COMPANY value
	 */
	public void setSellingCompany (java.lang.Integer _sellingCompany) {
		this._sellingCompany = _sellingCompany;
	}


	/**
	 * Return the value associated with the column: ACRES
	 */
	public java.math.BigDecimal getAcres () {
		return _acres;
	}

	/**
	 * Set the value related to the column: ACRES
	 * @param _acres the ACRES value
	 */
	public void setAcres (java.math.BigDecimal _acres) {
		this._acres = _acres;
	}


	/**
	 * Return the value associated with the column: COMPSELL
	 */
	public java.math.BigDecimal getCompsell () {
		return _compsell;
	}

	/**
	 * Set the value related to the column: COMPSELL
	 * @param _compsell the COMPSELL value
	 */
	public void setCompsell (java.math.BigDecimal _compsell) {
		this._compsell = _compsell;
	}


	/**
	 * Return the value associated with the column: MLSNUM
	 */
	public java.lang.String getMlsnum () {
		return _mlsnum;
	}

	/**
	 * Set the value related to the column: MLSNUM
	 * @param _mlsnum the MLSNUM value
	 */
	public void setMlsnum (java.lang.String _mlsnum) {
		this._mlsnum = _mlsnum;
	}


	/**
	 * Return the value associated with the column: DIRECTIONS
	 */
	public java.lang.String getDirections () {
		return _directions;
	}

	/**
	 * Set the value related to the column: DIRECTIONS
	 * @param _directions the DIRECTIONS value
	 */
	public void setDirections (java.lang.String _directions) {
		this._directions = _directions;
	}


	/**
	 * Return the value associated with the column: ROOMKITCHENDESC
	 */
	public java.lang.String getRoomkitchendesc () {
		return _roomkitchendesc;
	}

	/**
	 * Set the value related to the column: ROOMKITCHENDESC
	 * @param _roomkitchendesc the ROOMKITCHENDESC value
	 */
	public void setRoomkitchendesc (java.lang.String _roomkitchendesc) {
		this._roomkitchendesc = _roomkitchendesc;
	}


	/**
	 * Return the value associated with the column: SQFTSOURCE
	 */
	public java.lang.String getSqftsource () {
		return _sqftsource;
	}

	/**
	 * Set the value related to the column: SQFTSOURCE
	 * @param _sqftsource the SQFTSOURCE value
	 */
	public void setSqftsource (java.lang.String _sqftsource) {
		this._sqftsource = _sqftsource;
	}


	/**
	 * Return the value associated with the column: NUMFLOORS
	 */
	public java.math.BigDecimal getNumfloors () {
		return _numfloors;
	}

	/**
	 * Set the value related to the column: NUMFLOORS
	 * @param _numfloors the NUMFLOORS value
	 */
	public void setNumfloors (java.math.BigDecimal _numfloors) {
		this._numfloors = _numfloors;
	}


	/**
	 * Return the value associated with the column: FRONTAGEFEET
	 */
	public java.math.BigDecimal getFrontagefeet () {
		return _frontagefeet;
	}

	/**
	 * Set the value related to the column: FRONTAGEFEET
	 * @param _frontagefeet the FRONTAGEFEET value
	 */
	public void setFrontagefeet (java.math.BigDecimal _frontagefeet) {
		this._frontagefeet = _frontagefeet;
	}


	/**
	 * Return the value associated with the column: PENDINGDATE
	 */
	public java.util.Date getPendingdate () {
		return _pendingdate;
	}

	/**
	 * Set the value related to the column: PENDINGDATE
	 * @param _pendingdate the PENDINGDATE value
	 */
	public void setPendingdate (java.util.Date _pendingdate) {
		this._pendingdate = _pendingdate;
	}


	/**
	 * Return the value associated with the column: MULTIPLEPIN
	 */
	public java.lang.String getMultiplepin () {
		return _multiplepin;
	}

	/**
	 * Set the value related to the column: MULTIPLEPIN
	 * @param _multiplepin the MULTIPLEPIN value
	 */
	public void setMultiplepin (java.lang.String _multiplepin) {
		this._multiplepin = _multiplepin;
	}


	/**
	 * Return the value associated with the column: REALREMARKS
	 */
	public java.lang.String getRealremarks () {
		return _realremarks;
	}

	/**
	 * Set the value related to the column: REALREMARKS
	 * @param _realremarks the REALREMARKS value
	 */
	public void setRealremarks (java.lang.String _realremarks) {
		this._realremarks = _realremarks;
	}


	/**
	 * Return the value associated with the column: BATHSTOTAL
	 */
	public java.math.BigDecimal getBathstotal () {
		return _bathstotal;
	}

	/**
	 * Set the value related to the column: BATHSTOTAL
	 * @param _bathstotal the BATHSTOTAL value
	 */
	public void setBathstotal (java.math.BigDecimal _bathstotal) {
		this._bathstotal = _bathstotal;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER2NAME
	 */
	public java.lang.String getRoomother2name () {
		return _roomother2name;
	}

	/**
	 * Set the value related to the column: ROOMOTHER2NAME
	 * @param _roomother2name the ROOMOTHER2NAME value
	 */
	public void setRoomother2name (java.lang.String _roomother2name) {
		this._roomother2name = _roomother2name;
	}


	/**
	 * Return the value associated with the column: COMPBUY
	 */
	public java.math.BigDecimal getCompbuy () {
		return _compbuy;
	}

	/**
	 * Set the value related to the column: COMPBUY
	 * @param _compbuy the COMPBUY value
	 */
	public void setCompbuy (java.math.BigDecimal _compbuy) {
		this._compbuy = _compbuy;
	}


	/**
	 * Return the value associated with the column: NEWCONSTRUCTION
	 */
	public java.lang.String getNewconstruction () {
		return _newconstruction;
	}

	/**
	 * Set the value related to the column: NEWCONSTRUCTION
	 * @param _newconstruction the NEWCONSTRUCTION value
	 */
	public void setNewconstruction (java.lang.String _newconstruction) {
		this._newconstruction = _newconstruction;
	}


	/**
	 * Return the value associated with the column: ROOMS
	 */
	public java.math.BigDecimal getRooms () {
		return _rooms;
	}

	/**
	 * Set the value related to the column: ROOMS
	 * @param _rooms the ROOMS value
	 */
	public void setRooms (java.math.BigDecimal _rooms) {
		this._rooms = _rooms;
	}


	/**
	 * Return the value associated with the column: AGENTCOLIST
	 */
	public java.lang.String getAgentcolist () {
		return _agentcolist;
	}

	/**
	 * Set the value related to the column: AGENTCOLIST
	 * @param _agentcolist the AGENTCOLIST value
	 */
	public void setAgentcolist (java.lang.String _agentcolist) {
		this._agentcolist = _agentcolist;
	}


	/**
	 * Return the value associated with the column: OCCUPIED
	 */
	public java.lang.String getOccupied () {
		return _occupied;
	}

	/**
	 * Set the value related to the column: OCCUPIED
	 * @param _occupied the OCCUPIED value
	 */
	public void setOccupied (java.lang.String _occupied) {
		this._occupied = _occupied;
	}


	/**
	 * Return the value associated with the column: MONTHELECTRIC
	 */
	public java.math.BigDecimal getMonthelectric () {
		return _monthelectric;
	}

	/**
	 * Set the value related to the column: MONTHELECTRIC
	 * @param _monthelectric the MONTHELECTRIC value
	 */
	public void setMonthelectric (java.math.BigDecimal _monthelectric) {
		this._monthelectric = _monthelectric;
	}


	/**
	 * Return the value associated with the column: BED4LEVEL
	 */
	public java.lang.String getBed4level () {
		return _bed4level;
	}

	/**
	 * Set the value related to the column: BED4LEVEL
	 * @param _bed4level the BED4LEVEL value
	 */
	public void setBed4level (java.lang.String _bed4level) {
		this._bed4level = _bed4level;
	}


	/**
	 * Return the value associated with the column: ROOMOTHER2DESC
	 */
	public java.lang.String getRoomother2desc () {
		return _roomother2desc;
	}

	/**
	 * Set the value related to the column: ROOMOTHER2DESC
	 * @param _roomother2desc the ROOMOTHER2DESC value
	 */
	public void setRoomother2desc (java.lang.String _roomother2desc) {
		this._roomother2desc = _roomother2desc;
	}


	/**
	 * Return the value associated with the column: LISTTYPE
	 */
	public java.lang.String getListtype () {
		return _listtype;
	}

	/**
	 * Set the value related to the column: LISTTYPE
	 * @param _listtype the LISTTYPE value
	 */
	public void setListtype (java.lang.String _listtype) {
		this._listtype = _listtype;
	}


	/**
	 * Return the value associated with the column: agents
	 */
	public java.util.Set getAgents () {
		return this._agents;
	}

	/**
	 * Set the value related to the column: agents
	 * @param _agents the agents value
	 */
	public void setAgents (java.util.Set _agents) {
		this._agents = _agents;
	}
	
	public void addToAgents (Object obj) {
		if (null == this._agents) this._agents = new java.util.HashSet();
		this._agents.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.realtor.rets.database.base.BaseProperties)) return false;
		else {
			org.realtor.rets.database.base.BaseProperties mObj = (org.realtor.rets.database.base.BaseProperties) obj;
			if (null == this.getOid() || null == mObj.getOid()) return false;
			else return (this.getOid().equals(mObj.getOid()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getOid()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getOid().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}