package org.realtor.rets.database.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the property_codes table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="property_codes"
 */
public abstract class BasePropertyCodes  implements Serializable {

	public static String PROP_SHORT_VALUE = "ShortValue";
	public static String PROP_LONG_VALUE = "LongValue";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private org.realtor.rets.database.PropertyCodesPK _id;

	// fields
	private java.lang.String _shortValue;
	private java.lang.String _longValue;


	// constructors
	public BasePropertyCodes () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePropertyCodes (org.realtor.rets.database.PropertyCodesPK _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     */
	public org.realtor.rets.database.PropertyCodesPK getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (org.realtor.rets.database.PropertyCodesPK _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: SHORT_VALUE
	 */
	public java.lang.String getShortValue () {
		return _shortValue;
	}

	/**
	 * Set the value related to the column: SHORT_VALUE
	 * @param _shortValue the SHORT_VALUE value
	 */
	public void setShortValue (java.lang.String _shortValue) {
		this._shortValue = _shortValue;
	}


	/**
	 * Return the value associated with the column: LONG_VALUE
	 */
	public java.lang.String getLongValue () {
		return _longValue;
	}

	/**
	 * Set the value related to the column: LONG_VALUE
	 * @param _longValue the LONG_VALUE value
	 */
	public void setLongValue (java.lang.String _longValue) {
		this._longValue = _longValue;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.realtor.rets.database.base.BasePropertyCodes)) return false;
		else {
			org.realtor.rets.database.base.BasePropertyCodes mObj = (org.realtor.rets.database.base.BasePropertyCodes) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}