package org.realtor.rets.database.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the offices table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="offices"
 */
public abstract class BaseOffices  implements Serializable {

	public static String PROP_OFFICESTATUS = "Officestatus";
	public static String PROP_MODIFIED = "Modified";
	public static String PROP_OFFICEEMAIL = "Officeemail";
	public static String PROP_OID = "Oid";
	public static String PROP_STATE = "State";
	public static String PROP_ADDRESS1 = "Address1";
	public static String PROP_WEB = "Web";
	public static String PROP_ZIP = "Zip";
	public static String PROP_CITY = "City";
	public static String PROP_OFFICETYPE = "Officetype";
	public static String PROP_UIDCOMPANY = "Uidcompany";
	public static String PROP_OFFICEID = "Officeid";
	public static String PROP_PHONE = "Phone";
	public static String PROP_FAX = "Fax";
	public static String PROP_OFFICENAME = "Officename";
	public static String PROP_ADDRESS2 = "Address2";
	public static String PROP_ZIP4 = "Zip4";
	public static String PROP_UID = "Uid";
	public static String PROP_OPTINFLG = "Optinflg";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _oid;

	// fields
	private java.lang.String _officename;
	private java.lang.String _state;
	private java.lang.String _officetype;
	private java.lang.String _address2;
	private java.lang.String _web;
	private java.lang.String _fax;
	private java.lang.String _officestatus;
	private java.lang.String _uid;
	private java.util.Date _modified;
	private java.lang.String _optinflg;
	private java.lang.String _phone;
	private java.lang.String _officeemail;
	private java.lang.String _city;
	private java.lang.String _zip4;
	private java.lang.String _address1;
	private java.lang.String _zip;
	private java.lang.String _officeid;
	private java.lang.String _uidcompany;

	// collections
	private java.util.Set _agents;


	// constructors
	public BaseOffices () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseOffices (java.lang.Long _oid) {
		this.setOid(_oid);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="OID"
     */
	public java.lang.Long getOid () {
		return _oid;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _oid the new ID
	 */
	public void setOid (java.lang.Long _oid) {
		this._oid = _oid;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: OFFICENAME
	 */
	public java.lang.String getOfficename () {
		return _officename;
	}

	/**
	 * Set the value related to the column: OFFICENAME
	 * @param _officename the OFFICENAME value
	 */
	public void setOfficename (java.lang.String _officename) {
		this._officename = _officename;
	}


	/**
	 * Return the value associated with the column: STATE
	 */
	public java.lang.String getState () {
		return _state;
	}

	/**
	 * Set the value related to the column: STATE
	 * @param _state the STATE value
	 */
	public void setState (java.lang.String _state) {
		this._state = _state;
	}


	/**
	 * Return the value associated with the column: OFFICETYPE
	 */
	public java.lang.String getOfficetype () {
		return _officetype;
	}

	/**
	 * Set the value related to the column: OFFICETYPE
	 * @param _officetype the OFFICETYPE value
	 */
	public void setOfficetype (java.lang.String _officetype) {
		this._officetype = _officetype;
	}


	/**
	 * Return the value associated with the column: ADDRESS2
	 */
	public java.lang.String getAddress2 () {
		return _address2;
	}

	/**
	 * Set the value related to the column: ADDRESS2
	 * @param _address2 the ADDRESS2 value
	 */
	public void setAddress2 (java.lang.String _address2) {
		this._address2 = _address2;
	}


	/**
	 * Return the value associated with the column: WEB
	 */
	public java.lang.String getWeb () {
		return _web;
	}

	/**
	 * Set the value related to the column: WEB
	 * @param _web the WEB value
	 */
	public void setWeb (java.lang.String _web) {
		this._web = _web;
	}


	/**
	 * Return the value associated with the column: FAX
	 */
	public java.lang.String getFax () {
		return _fax;
	}

	/**
	 * Set the value related to the column: FAX
	 * @param _fax the FAX value
	 */
	public void setFax (java.lang.String _fax) {
		this._fax = _fax;
	}


	/**
	 * Return the value associated with the column: OFFICESTATUS
	 */
	public java.lang.String getOfficestatus () {
		return _officestatus;
	}

	/**
	 * Set the value related to the column: OFFICESTATUS
	 * @param _officestatus the OFFICESTATUS value
	 */
	public void setOfficestatus (java.lang.String _officestatus) {
		this._officestatus = _officestatus;
	}


	/**
	 * Return the value associated with the column: UID
	 */
	public java.lang.String getUid () {
		return _uid;
	}

	/**
	 * Set the value related to the column: UID
	 * @param _uid the UID value
	 */
	public void setUid (java.lang.String _uid) {
		this._uid = _uid;
	}


	/**
	 * Return the value associated with the column: MODIFIED
	 */
	public java.util.Date getModified () {
		return _modified;
	}

	/**
	 * Set the value related to the column: MODIFIED
	 * @param _modified the MODIFIED value
	 */
	public void setModified (java.util.Date _modified) {
		this._modified = _modified;
	}


	/**
	 * Return the value associated with the column: OPTINFLG
	 */
	public java.lang.String getOptinflg () {
		return _optinflg;
	}

	/**
	 * Set the value related to the column: OPTINFLG
	 * @param _optinflg the OPTINFLG value
	 */
	public void setOptinflg (java.lang.String _optinflg) {
		this._optinflg = _optinflg;
	}


	/**
	 * Return the value associated with the column: PHONE
	 */
	public java.lang.String getPhone () {
		return _phone;
	}

	/**
	 * Set the value related to the column: PHONE
	 * @param _phone the PHONE value
	 */
	public void setPhone (java.lang.String _phone) {
		this._phone = _phone;
	}


	/**
	 * Return the value associated with the column: OFFICEEMAIL
	 */
	public java.lang.String getOfficeemail () {
		return _officeemail;
	}

	/**
	 * Set the value related to the column: OFFICEEMAIL
	 * @param _officeemail the OFFICEEMAIL value
	 */
	public void setOfficeemail (java.lang.String _officeemail) {
		this._officeemail = _officeemail;
	}


	/**
	 * Return the value associated with the column: CITY
	 */
	public java.lang.String getCity () {
		return _city;
	}

	/**
	 * Set the value related to the column: CITY
	 * @param _city the CITY value
	 */
	public void setCity (java.lang.String _city) {
		this._city = _city;
	}


	/**
	 * Return the value associated with the column: ZIP4
	 */
	public java.lang.String getZip4 () {
		return _zip4;
	}

	/**
	 * Set the value related to the column: ZIP4
	 * @param _zip4 the ZIP4 value
	 */
	public void setZip4 (java.lang.String _zip4) {
		this._zip4 = _zip4;
	}


	/**
	 * Return the value associated with the column: ADDRESS1
	 */
	public java.lang.String getAddress1 () {
		return _address1;
	}

	/**
	 * Set the value related to the column: ADDRESS1
	 * @param _address1 the ADDRESS1 value
	 */
	public void setAddress1 (java.lang.String _address1) {
		this._address1 = _address1;
	}


	/**
	 * Return the value associated with the column: ZIP
	 */
	public java.lang.String getZip () {
		return _zip;
	}

	/**
	 * Set the value related to the column: ZIP
	 * @param _zip the ZIP value
	 */
	public void setZip (java.lang.String _zip) {
		this._zip = _zip;
	}


	/**
	 * Return the value associated with the column: OFFICEID
	 */
	public java.lang.String getOfficeid () {
		return _officeid;
	}

	/**
	 * Set the value related to the column: OFFICEID
	 * @param _officeid the OFFICEID value
	 */
	public void setOfficeid (java.lang.String _officeid) {
		this._officeid = _officeid;
	}


	/**
	 * Return the value associated with the column: UIDCOMPANY
	 */
	public java.lang.String getUidcompany () {
		return _uidcompany;
	}

	/**
	 * Set the value related to the column: UIDCOMPANY
	 * @param _uidcompany the UIDCOMPANY value
	 */
	public void setUidcompany (java.lang.String _uidcompany) {
		this._uidcompany = _uidcompany;
	}


	/**
	 * Return the value associated with the column: agents
	 */
	public java.util.Set getAgents () {
		return this._agents;
	}

	/**
	 * Set the value related to the column: agents
	 * @param _agents the agents value
	 */
	public void setAgents (java.util.Set _agents) {
		this._agents = _agents;
	}
	
	public void addToAgents (Object obj) {
		if (null == this._agents) this._agents = new java.util.HashSet();
		this._agents.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.realtor.rets.database.base.BaseOffices)) return false;
		else {
			org.realtor.rets.database.base.BaseOffices mObj = (org.realtor.rets.database.base.BaseOffices) obj;
			if (null == this.getOid() || null == mObj.getOid()) return false;
			else return (this.getOid().equals(mObj.getOid()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getOid()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getOid().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}