package org.realtor.rets.database.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the agents table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="agents"
 */
public abstract class BaseAgents  implements Serializable {

	public static String PROP_LASTNAME = "Lastname";
	public static String PROP_PUBID = "Pubid";
	public static String PROP_OID = "Oid";
	public static String PROP_UIDOFFICE = "Uidoffice";
	public static String PROP_MIDDLENAME = "Middlename";
	public static String PROP_PREFERREDFAX = "Preferredfax";
	public static String PROP_FIRSTNAME = "Firstname";
	public static String PROP_CITY = "City";
	public static String PROP_HOMEFAX = "Homefax";
	public static String PROP_PASSWORD = "Password";
	public static String PROP_HOMEPHONE = "Homephone";
	public static String PROP_ZIP4 = "Zip4";
	public static String PROP_UID = "Uid";
	public static String PROP_MODIFIED = "Modified";
	public static String PROP_MOBILEPHONE = "Mobilephone";
	public static String PROP_LICENSENO = "Licenseno";
	public static String PROP_GENDER = "Gender";
	public static String PROP_STATE = "State";
	public static String PROP_ADDRESS1 = "Address1";
	public static String PROP_PREFERREDPHONE = "Preferredphone";
	public static String PROP_WEB = "Web";
	public static String PROP_ZIP = "Zip";
	public static String PROP_ONLINESTATUS = "Onlinestatus";
	public static String PROP_PERSONALTITLE = "Personaltitle";
	public static String PROP_MLSSTATUS = "Mlsstatus";
	public static String PROP_PAGERNUMBER = "Pagernumber";
	public static String PROP_EMAIL = "Email";
	public static String PROP_LOGINID = "Loginid";
	public static String PROP_MEMBERTYPE = "Membertype";
	public static String PROP_ADDRESS2 = "Address2";
	public static String PROP_FULLNAME = "Fullname";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _oid;

	// fields
	private java.lang.String _uidoffice;
	private java.lang.String _state;
	private java.lang.String _membertype;
	private java.lang.String _mobilephone;
	private java.lang.String _web;
	private java.lang.String _loginid;
	private java.lang.String _personaltitle;
	private java.lang.String _lastname;
	private java.lang.String _homefax;
	private java.lang.String _preferredphone;
	private java.lang.String _email;
	private java.util.Date _modified;
	private java.lang.String _onlinestatus;
	private java.lang.String _zip4;
	private java.lang.String _zip;
	private java.lang.String _middlename;
	private java.lang.String _preferredfax;
	private java.lang.String _address2;
	private java.lang.String _password;
	private java.lang.String _fullname;
	private java.lang.String _mlsstatus;
	private java.lang.String _firstname;
	private java.lang.String _uid;
	private java.lang.String _pubid;
	private java.lang.String _licenseno;
	private java.lang.String _homephone;
	private java.lang.String _city;
	private java.lang.String _gender;
	private java.lang.String _address1;
	private java.lang.String _pagernumber;

	// collections
	private java.util.Set _properties;
	private java.util.Set _offices;


	// constructors
	public BaseAgents () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAgents (java.lang.Long _oid) {
		this.setOid(_oid);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="OID"
     */
	public java.lang.Long getOid () {
		return _oid;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _oid the new ID
	 */
	public void setOid (java.lang.Long _oid) {
		this._oid = _oid;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: UIDOFFICE
	 */
	public java.lang.String getUidoffice () {
		return _uidoffice;
	}

	/**
	 * Set the value related to the column: UIDOFFICE
	 * @param _uidoffice the UIDOFFICE value
	 */
	public void setUidoffice (java.lang.String _uidoffice) {
		this._uidoffice = _uidoffice;
	}


	/**
	 * Return the value associated with the column: STATE
	 */
	public java.lang.String getState () {
		return _state;
	}

	/**
	 * Set the value related to the column: STATE
	 * @param _state the STATE value
	 */
	public void setState (java.lang.String _state) {
		this._state = _state;
	}


	/**
	 * Return the value associated with the column: MEMBERTYPE
	 */
	public java.lang.String getMembertype () {
		return _membertype;
	}

	/**
	 * Set the value related to the column: MEMBERTYPE
	 * @param _membertype the MEMBERTYPE value
	 */
	public void setMembertype (java.lang.String _membertype) {
		this._membertype = _membertype;
	}


	/**
	 * Return the value associated with the column: MOBILEPHONE
	 */
	public java.lang.String getMobilephone () {
		return _mobilephone;
	}

	/**
	 * Set the value related to the column: MOBILEPHONE
	 * @param _mobilephone the MOBILEPHONE value
	 */
	public void setMobilephone (java.lang.String _mobilephone) {
		this._mobilephone = _mobilephone;
	}


	/**
	 * Return the value associated with the column: WEB
	 */
	public java.lang.String getWeb () {
		return _web;
	}

	/**
	 * Set the value related to the column: WEB
	 * @param _web the WEB value
	 */
	public void setWeb (java.lang.String _web) {
		this._web = _web;
	}


	/**
	 * Return the value associated with the column: LOGINID
	 */
	public java.lang.String getLoginid () {
		return _loginid;
	}

	/**
	 * Set the value related to the column: LOGINID
	 * @param _loginid the LOGINID value
	 */
	public void setLoginid (java.lang.String _loginid) {
		this._loginid = _loginid;
	}


	/**
	 * Return the value associated with the column: PERSONALTITLE
	 */
	public java.lang.String getPersonaltitle () {
		return _personaltitle;
	}

	/**
	 * Set the value related to the column: PERSONALTITLE
	 * @param _personaltitle the PERSONALTITLE value
	 */
	public void setPersonaltitle (java.lang.String _personaltitle) {
		this._personaltitle = _personaltitle;
	}


	/**
	 * Return the value associated with the column: LASTNAME
	 */
	public java.lang.String getLastname () {
		return _lastname;
	}

	/**
	 * Set the value related to the column: LASTNAME
	 * @param _lastname the LASTNAME value
	 */
	public void setLastname (java.lang.String _lastname) {
		this._lastname = _lastname;
	}


	/**
	 * Return the value associated with the column: HOMEFAX
	 */
	public java.lang.String getHomefax () {
		return _homefax;
	}

	/**
	 * Set the value related to the column: HOMEFAX
	 * @param _homefax the HOMEFAX value
	 */
	public void setHomefax (java.lang.String _homefax) {
		this._homefax = _homefax;
	}


	/**
	 * Return the value associated with the column: PREFERREDPHONE
	 */
	public java.lang.String getPreferredphone () {
		return _preferredphone;
	}

	/**
	 * Set the value related to the column: PREFERREDPHONE
	 * @param _preferredphone the PREFERREDPHONE value
	 */
	public void setPreferredphone (java.lang.String _preferredphone) {
		this._preferredphone = _preferredphone;
	}


	/**
	 * Return the value associated with the column: EMAIL
	 */
	public java.lang.String getEmail () {
		return _email;
	}

	/**
	 * Set the value related to the column: EMAIL
	 * @param _email the EMAIL value
	 */
	public void setEmail (java.lang.String _email) {
		this._email = _email;
	}


	/**
	 * Return the value associated with the column: MODIFIED
	 */
	public java.util.Date getModified () {
		return _modified;
	}

	/**
	 * Set the value related to the column: MODIFIED
	 * @param _modified the MODIFIED value
	 */
	public void setModified (java.util.Date _modified) {
		this._modified = _modified;
	}


	/**
	 * Return the value associated with the column: ONLINESTATUS
	 */
	public java.lang.String getOnlinestatus () {
		return _onlinestatus;
	}

	/**
	 * Set the value related to the column: ONLINESTATUS
	 * @param _onlinestatus the ONLINESTATUS value
	 */
	public void setOnlinestatus (java.lang.String _onlinestatus) {
		this._onlinestatus = _onlinestatus;
	}


	/**
	 * Return the value associated with the column: ZIP4
	 */
	public java.lang.String getZip4 () {
		return _zip4;
	}

	/**
	 * Set the value related to the column: ZIP4
	 * @param _zip4 the ZIP4 value
	 */
	public void setZip4 (java.lang.String _zip4) {
		this._zip4 = _zip4;
	}


	/**
	 * Return the value associated with the column: ZIP
	 */
	public java.lang.String getZip () {
		return _zip;
	}

	/**
	 * Set the value related to the column: ZIP
	 * @param _zip the ZIP value
	 */
	public void setZip (java.lang.String _zip) {
		this._zip = _zip;
	}


	/**
	 * Return the value associated with the column: MIDDLENAME
	 */
	public java.lang.String getMiddlename () {
		return _middlename;
	}

	/**
	 * Set the value related to the column: MIDDLENAME
	 * @param _middlename the MIDDLENAME value
	 */
	public void setMiddlename (java.lang.String _middlename) {
		this._middlename = _middlename;
	}


	/**
	 * Return the value associated with the column: PREFERREDFAX
	 */
	public java.lang.String getPreferredfax () {
		return _preferredfax;
	}

	/**
	 * Set the value related to the column: PREFERREDFAX
	 * @param _preferredfax the PREFERREDFAX value
	 */
	public void setPreferredfax (java.lang.String _preferredfax) {
		this._preferredfax = _preferredfax;
	}


	/**
	 * Return the value associated with the column: ADDRESS2
	 */
	public java.lang.String getAddress2 () {
		return _address2;
	}

	/**
	 * Set the value related to the column: ADDRESS2
	 * @param _address2 the ADDRESS2 value
	 */
	public void setAddress2 (java.lang.String _address2) {
		this._address2 = _address2;
	}


	/**
	 * Return the value associated with the column: PASSWORD
	 */
	public java.lang.String getPassword () {
		return _password;
	}

	/**
	 * Set the value related to the column: PASSWORD
	 * @param _password the PASSWORD value
	 */
	public void setPassword (java.lang.String _password) {
		this._password = _password;
	}


	/**
	 * Return the value associated with the column: FULLNAME
	 */
	public java.lang.String getFullname () {
		return _fullname;
	}

	/**
	 * Set the value related to the column: FULLNAME
	 * @param _fullname the FULLNAME value
	 */
	public void setFullname (java.lang.String _fullname) {
		this._fullname = _fullname;
	}


	/**
	 * Return the value associated with the column: MLSSTATUS
	 */
	public java.lang.String getMlsstatus () {
		return _mlsstatus;
	}

	/**
	 * Set the value related to the column: MLSSTATUS
	 * @param _mlsstatus the MLSSTATUS value
	 */
	public void setMlsstatus (java.lang.String _mlsstatus) {
		this._mlsstatus = _mlsstatus;
	}


	/**
	 * Return the value associated with the column: FIRSTNAME
	 */
	public java.lang.String getFirstname () {
		return _firstname;
	}

	/**
	 * Set the value related to the column: FIRSTNAME
	 * @param _firstname the FIRSTNAME value
	 */
	public void setFirstname (java.lang.String _firstname) {
		this._firstname = _firstname;
	}


	/**
	 * Return the value associated with the column: UID
	 */
	public java.lang.String getUid () {
		return _uid;
	}

	/**
	 * Set the value related to the column: UID
	 * @param _uid the UID value
	 */
	public void setUid (java.lang.String _uid) {
		this._uid = _uid;
	}


	/**
	 * Return the value associated with the column: PUBID
	 */
	public java.lang.String getPubid () {
		return _pubid;
	}

	/**
	 * Set the value related to the column: PUBID
	 * @param _pubid the PUBID value
	 */
	public void setPubid (java.lang.String _pubid) {
		this._pubid = _pubid;
	}


	/**
	 * Return the value associated with the column: LICENSENO
	 */
	public java.lang.String getLicenseno () {
		return _licenseno;
	}

	/**
	 * Set the value related to the column: LICENSENO
	 * @param _licenseno the LICENSENO value
	 */
	public void setLicenseno (java.lang.String _licenseno) {
		this._licenseno = _licenseno;
	}


	/**
	 * Return the value associated with the column: HOMEPHONE
	 */
	public java.lang.String getHomephone () {
		return _homephone;
	}

	/**
	 * Set the value related to the column: HOMEPHONE
	 * @param _homephone the HOMEPHONE value
	 */
	public void setHomephone (java.lang.String _homephone) {
		this._homephone = _homephone;
	}


	/**
	 * Return the value associated with the column: CITY
	 */
	public java.lang.String getCity () {
		return _city;
	}

	/**
	 * Set the value related to the column: CITY
	 * @param _city the CITY value
	 */
	public void setCity (java.lang.String _city) {
		this._city = _city;
	}


	/**
	 * Return the value associated with the column: GENDER
	 */
	public java.lang.String getGender () {
		return _gender;
	}

	/**
	 * Set the value related to the column: GENDER
	 * @param _gender the GENDER value
	 */
	public void setGender (java.lang.String _gender) {
		this._gender = _gender;
	}


	/**
	 * Return the value associated with the column: ADDRESS1
	 */
	public java.lang.String getAddress1 () {
		return _address1;
	}

	/**
	 * Set the value related to the column: ADDRESS1
	 * @param _address1 the ADDRESS1 value
	 */
	public void setAddress1 (java.lang.String _address1) {
		this._address1 = _address1;
	}


	/**
	 * Return the value associated with the column: PAGERNUMBER
	 */
	public java.lang.String getPagernumber () {
		return _pagernumber;
	}

	/**
	 * Set the value related to the column: PAGERNUMBER
	 * @param _pagernumber the PAGERNUMBER value
	 */
	public void setPagernumber (java.lang.String _pagernumber) {
		this._pagernumber = _pagernumber;
	}


	/**
	 * Return the value associated with the column: properties
	 */
	public java.util.Set getProperties () {
		return this._properties;
	}

	/**
	 * Set the value related to the column: properties
	 * @param _properties the properties value
	 */
	public void setProperties (java.util.Set _properties) {
		this._properties = _properties;
	}
	
	public void addToProperties (Object obj) {
		if (null == this._properties) this._properties = new java.util.HashSet();
		this._properties.add(obj);
	}



	/**
	 * Return the value associated with the column: offices
	 */
	public java.util.Set getOffices () {
		return this._offices;
	}

	/**
	 * Set the value related to the column: offices
	 * @param _offices the offices value
	 */
	public void setOffices (java.util.Set _offices) {
		this._offices = _offices;
	}
	
	public void addToOffices (Object obj) {
		if (null == this._offices) this._offices = new java.util.HashSet();
		this._offices.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.realtor.rets.database.base.BaseAgents)) return false;
		else {
			org.realtor.rets.database.base.BaseAgents mObj = (org.realtor.rets.database.base.BaseAgents) obj;
			if (null == this.getOid() || null == mObj.getOid()) return false;
			else return (this.getOid().equals(mObj.getOid()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getOid()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getOid().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}